<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>Loket REST API Client</Description>
    <TargetFrameworks>netstandard2.1;net8.0</TargetFrameworks>
    <PackageTags>Loket;Loket;C#;APIs;Client;Generated;Kiota</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="kiota-lock.json" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Bcl.TimeProvider" Version="8.0.1" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.3" />
    <PackageReference Include="Microsoft.Kiota.Bundle" Version="2.0.0" />
  </ItemGroup>
</Project>