# Note : this is for future use, it does work, but the generated code + dlls will be quite large (60 MB).

$SourcePath = "./src/Loket.Api.Client"
$OutputPath = "./src/Loket.Api.Client/IBuilders.cs"

Write-Host "Scanning for RequestBuilder classes in: $SourcePath" -ForegroundColor Green

# Find all RequestBuilder files in the Generated folder
$generatedPath = Join-Path $SourcePath "Generated"
if (-not (Test-Path $generatedPath)) {
    Write-Error "Generated folder not found at: $generatedPath"
    exit 1
}

Write-Host "Extracting RequestBuilder classes from Generated folder..." -ForegroundColor Yellow

# Extract all RequestBuilder classes from Generated folder
$builders = @()
$requestBuilderFiles = Get-ChildItem $generatedPath -Recurse -Name "*RequestBuilder.cs"

Write-Host "Found $($requestBuilderFiles.Count) RequestBuilder files" -ForegroundColor Cyan

foreach ($file in $requestBuilderFiles) {
    $fullPath = Join-Path $generatedPath $file
    try {
        $content = Get-Content $fullPath -Raw -ErrorAction Stop
        if ($content -match 'namespace\s+([\w\.]+)\s*\{[\s\S]*?public\s+partial\s+class\s+(\w*RequestBuilder)\s*:\s*BaseRequestBuilder') {
            $builders += "$($matches[1]).$($matches[2])"
        }
    }
    catch {
        Write-Warning "Failed to read file: $fullPath - $($_.Exception.Message)"
    }
}

Write-Host "Extracted $($builders.Count) RequestBuilder classes from Generated folder" -ForegroundColor Cyan

if ($builders.Count -eq 0) {
    Write-Error "No RequestBuilder classes found. Please check the source path."
    exit 1
}

# Sort all builders
$builders = $builders | Sort-Object

Write-Host "Generating IBuilders.cs with $($builders.Count) interfaces..." -ForegroundColor Yellow

# Generate the IBuilders.cs content
$content = @"
// <auto-generated/>
// This file contains interface declarations for all Builder classes in the Loket Api Client project using https://github.com/StefH/ProxyInterfaceSourceGenerator.
// Do not modify this file manually. It is generated by Generate-IBuilders.ps1 script.
// Generated on: $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")

using ProxyInterfaceGenerator;

"@

# Group builders by namespace
$namespaceGroups = $builders | Group-Object { ($_ -split '\.')[0..($_.Split('.').Length-2)] -join '.' }

foreach ($group in $namespaceGroups) {
    $namespace = $group.Name
    $content += "`r`nnamespace $namespace`r`n{`r`n"
    
    foreach ($builder in $group.Group) {
        $parts = $builder -split '\.'
        $className = $parts[-1]
        $interfaceName = "I$className"
        
        $content += "    [Proxy<$className>(true)]`r`n"
        $content += "    public partial interface $interfaceName;`r`n"
    }
    
    $content += "}`r`n"
}

# Write to IBuilders.cs
try {
    $content | Out-File $OutputPath -Encoding UTF8 -ErrorAction Stop
    Write-Host "Successfully generated IBuilders.cs at: $OutputPath" -ForegroundColor Green
    Write-Host "File contains $($builders.Count) interface declarations" -ForegroundColor Green
    
    # Get file size for confirmation
    $fileInfo = Get-Item $OutputPath
    Write-Host "File size: $([math]::Round($fileInfo.Length / 1KB, 2)) KB" -ForegroundColor Cyan
    Write-Host "Total lines: $(($content -split "`r`n").Count)" -ForegroundColor Cyan
}
catch {
    Write-Error "Failed to write IBuilders.cs file: $($_.Exception.Message)"
    exit 1
}

Write-Host "`r`nScript completed successfully!" -ForegroundColor Green
Write-Host "Summary:" -ForegroundColor Yellow
Write-Host "  - Processed $($requestBuilderFiles.Count) RequestBuilder files" -ForegroundColor White
Write-Host "  - Generated $($builders.Count) interface declarations" -ForegroundColor White
Write-Host "  - Output file: $OutputPath" -ForegroundColor White