# Kiota generation script for Loket API client in C#

$buildersGeneratedPath = "src/Loket.Api.Client/Generated/Api/V2"
$modelsPath = "./src/Loket.Api.Client/Generated/Models"
$extensionsModelsPath = "./src/Loket.Api.Client/Extensions/Models"

Write-Output "⚙️ Generating C# client code"
kiota generate `
    --cc `
    --ad false `
    --openapi "./resources/Loket-openapi.json" `
    --clean-output `
    --language CSharp `
    --output "./src/Loket.Api.Client/Generated" `
    --namespace-name "Loket.Api.Client" `
    --class-name "LoketServiceClient" `

Write-Output "✅ Generating C# client code completed"

$modelFiles = Get-ChildItem -Path $modelsPath -Filter "*.cs" | Where-Object {
    $_.Name -notlike "*Post.cs" -and $_.Name -notlike "*Put.cs" -and $_.Name -notlike "*_Response.cs" -and $_.Name -notlike "*Post_Response.cs" -and $_.Name -notlike "*Put_Response.cs" -and $_.Name -notlike "*_Results.cs" -and $_.Name -notlike "LoketMetadata*.cs" -and $_.Name -notlike "ODataError*.cs" -and $_.Name -notlike "ODataDeferred*.cs" -and $_.Name -notlike "ODataNext*.cs"
}

Write-Output "🔄 Generating partial model classes to add PropertyMapping"
foreach ($file in $modelFiles) {
    $content = Get-Content -Path $file.FullName -Raw

    if ($content -notmatch 'public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers\(\)') {
        continue
    }

    # Extract property mappings from GetFieldDeserializers method
    $pattern = '{\s*"([^"]+)",\s*n\s*=>\s*{\s*(\w+)\s*='
    $regexMatches = [regex]::Matches($content, $pattern)

    $mappings = @()
    foreach ($match in $regexMatches) {
        $jsonKey = $match.Groups[1].Value
        $propertyName = $match.Groups[2].Value
        $mappings += "        { nameof($propertyName), `"$jsonKey`" }"
    }

    $propertyMappingCode = @"
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
$($mappings -join ",`r`n")
    };
"@

    $className = [System.IO.Path]::GetFileNameWithoutExtension($file.Name)
    $newContent = "// <auto-generated/>`r`nnamespace Loket.Api.Client.Models;`r`n`r`npublic partial class ${className}`r`n{`r`n" + $propertyMappingCode + "`r`n}"

    $newFilePath = Join-Path $extensionsModelsPath $file.Name
    Set-Content -Path $newFilePath -Value $newContent -Encoding UTF8
}

Write-Output "✅ Generating partial model classes completed"