// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class AbpFundsCollectivePatch
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(AbpFundId), "abpFundId" },
        { nameof(EmploymentId), "employmentId" },
        { nameof(EndDate), "endDate" }
    };
}
