// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class AbsencePutGetObject_progress
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(CurrentIncapacityPercentage), "currentIncapacityPercentage" },
        { nameof(EndOfAbsence), "endOfAbsence" },
        { nameof(StartDate), "startDate" }
    };
}
