// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class AbsenceStatisticsDataObject
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(ClientNumber), "clientNumber" },
        { nameof(Department), "department" },
        { nameof(EmployeeNumber), "employeeNumber" },
        { nameof(FormattedName), "formattedName" },
        { nameof(Function), "function" },
        { nameof(IncomeRelationshipNumber), "incomeRelationshipNumber" },
        { nameof(Month), "month" },
        { nameof(PercentageWeightedAbsenteeism), "percentageWeightedAbsenteeism" },
        { nameof(PercentageWeightedAbsenteeismLong), "percentageWeightedAbsenteeismLong" },
        { nameof(PercentageWeightedAbsenteeismMedium), "percentageWeightedAbsenteeismMedium" },
        { nameof(PercentageWeightedAbsenteeismShort), "percentageWeightedAbsenteeismShort" },
        { nameof(Year), "year" }
    };
}
