// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class AbsenceProgressObject
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Comments), "comments" },
        { nameof(EndDate), "endDate" },
        { nameof(Id), "id" },
        { nameof(IncapacityPercentage), "incapacityPercentage" },
        { nameof(StartDate), "startDate" },
        { nameof(TypeOfWorkResumption), "typeOfWorkResumption" }
    };
}
