// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class AbsencePostObject
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(AccidentType), "accidentType" },
        { nameof(ActionToBeTakenByOccupationalHealthAndSafetyService), "actionToBeTakenByOccupationalHealthAndSafetyService" },
        { nameof(CaseManager), "caseManager" },
        { nameof(CauseOfAbsence), "causeOfAbsence" },
        { nameof(Comments), "comments" },
        { nameof(ContactInformation), "contactInformation" },
        { nameof(ExpectedDateOfChildbirth), "expectedDateOfChildbirth" },
        { nameof(ExpectedDuration), "expectedDuration" },
        { nameof(ExpectedEndDateOfMaternityLeave), "expectedEndDateOfMaternityLeave" },
        { nameof(HasMobilityIssue), "hasMobilityIssue" },
        { nameof(HoursWorkedOnFirstDayOfAbsence), "hoursWorkedOnFirstDayOfAbsence" },
        { nameof(Id), "id" },
        { nameof(IsDisruptedEmploymentRelationship), "isDisruptedEmploymentRelationship" },
        { nameof(IsHospitalised), "isHospitalised" },
        { nameof(IsRecoveredWithinTwoWeeks), "isRecoveredWithinTwoWeeks" },
        { nameof(IsThirdPartyLiability), "isThirdPartyLiability" },
        { nameof(IsWorkRelatedIllness), "isWorkRelatedIllness" },
        { nameof(Progress), "progress" },
        { nameof(Reintegration), "reintegration" }
    };
}
