// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class AccrualMultiGetObject_leavePolicyAccrual
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Accrual), "accrual" },
        { nameof(AccrualAgeBasedLeave), "accrualAgeBasedLeave" },
        { nameof(AccrualWageBasedLeave), "accrualWageBasedLeave" },
        { nameof(AccrualYearsOfServiceBasedLeave), "accrualYearsOfServiceBasedLeave" },
        { nameof(LeaveType), "leaveType" }
    };
}
