// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class AddressObject
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Address), "address" },
        { nameof(PointOfInterest), "pointOfInterest" },
        { nameof(Position), "position" }
    };
}
