// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class AddressObject_address
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(CountryCode), "countryCode" },
        { nameof(FreeformAddress), "freeformAddress" }
    };
}
