// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class Administration
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(ClientNumber), "clientNumber" },
        { nameof(Description), "description" },
        { nameof(EmployerId), "employerId" },
        { nameof(EndDate), "endDate" },
        { nameof(Id), "id" },
        { nameof(IsPayrollAdministration), "isPayrollAdministration" },
        { nameof(StartDate), "startDate" },
        { nameof(WageTaxNumber), "wageTaxNumber" }
    };
}
