// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class AllEmployerUsersForAProvider_employerUser
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(AccessStatus), "accessStatus" },
        { nameof(AuthorizationSet), "authorizationSet" },
        { nameof(AzureActiveDirectory), "azureActiveDirectory" },
        { nameof(ContactInformation), "contactInformation" },
        { nameof(DateTimeCreation), "dateTimeCreation" },
        { nameof(DateTimeLastLogin), "dateTimeLastLogin" },
        { nameof(HasAccessToPayrollingTestData), "hasAccessToPayrollingTestData" },
        { nameof(HasConnectedApplications), "hasConnectedApplications" },
        { nameof(HasIntegrations), "hasIntegrations" },
        { nameof(HasMultiFactorAuthentication), "hasMultiFactorAuthentication" },
        { nameof(Id), "id" },
        { nameof(IsDepartmentManager), "isDepartmentManager" },
        { nameof(IsLinkedToMultipleEmployers), "isLinkedToMultipleEmployers" },
        { nameof(LoginMethod), "loginMethod" },
        { nameof(PersonalDetails), "personalDetails" },
        { nameof(TwoFactorAuthenticationRequired), "twoFactorAuthenticationRequired" },
        { nameof(UserCustomSpecifiedRole), "userCustomSpecifiedRole" },
        { nameof(UserName), "userName" },
        { nameof(UserSpecifiedRole), "userSpecifiedRole" }
    };
}
