// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class AllEmployerUsersForAProvider
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Employer), "employer" },
        { nameof(EmployerUser), "employerUser" }
    };
}
