// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class AllEmployerUsersForAProvider_employer_providerSettings
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(AdministrationNumber), "administrationNumber" },
        { nameof(GroupCode), "groupCode" }
    };
}
