// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class AnnouncementSummary
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(EmployerId), "employerId" },
        { nameof(NumberOfUnreadUnexpiredAnnouncements), "numberOfUnreadUnexpiredAnnouncements" }
    };
}
