// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class Announcement
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(CreationDate), "creationDate" },
        { nameof(Description), "description" },
        { nameof(EffectiveDate), "effectiveDate" },
        { nameof(ExpirationDate), "expirationDate" },
        { nameof(Id), "id" },
        { nameof(IsExpired), "isExpired" },
        { nameof(IsRead), "isRead" },
        { nameof(Subject), "subject" }
    };
}
