// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class AnnouncementProviderDetail
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(CreationDate), "creationDate" },
        { nameof(Description), "description" },
        { nameof(EffectiveDate), "effectiveDate" },
        { nameof(Employer), "employer" },
        { nameof(EmployerId), "employerId" },
        { nameof(EmployerLogo), "employerLogo" },
        { nameof(EmployerName), "employerName" },
        { nameof(ExpirationDate), "expirationDate" },
        { nameof(Id), "id" },
        { nameof(IsExpired), "isExpired" },
        { nameof(IsRead), "isRead" },
        { nameof(PayrollAdministration), "payrollAdministration" },
        { nameof(Subject), "subject" }
    };
}
