// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class ApgPensionDeclaration_responseMessages
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(DatetimeOfMessageReceipt), "datetimeOfMessageReceipt" },
        { nameof(DatetimeOfRegistration), "datetimeOfRegistration" },
        { nameof(Description), "description" }
    };
}
