// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class ApplicationAuthorizations
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Activity), "activity" },
        { nameof(AllowedRoles), "allowedRoles" },
        { nameof(DisplayName), "displayName" },
        { nameof(Id), "id" },
        { nameof(RequiredEmployerModules), "requiredEmployerModules" },
        { nameof(RequiredUserAuthorizations), "requiredUserAuthorizations" }
    };
}
