// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class Application
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(ActivationUrl), "activationUrl" },
        { nameof(ApplicationTypes), "applicationTypes" },
        { nameof(DateAddedToStore), "dateAddedToStore" },
        { nameof(Id), "id" },
        { nameof(IsActivatedForEmployer), "isActivatedForEmployer" },
        { nameof(IsHighlighted), "isHighlighted" },
        { nameof(Logo), "logo" },
        { nameof(MarketplaceDescription), "marketplaceDescription" },
        { nameof(MarketplaceSummary), "marketplaceSummary" },
        { nameof(Name), "name" },
        { nameof(ProductType), "productType" },
        { nameof(TargetIndustries), "targetIndustries" },
        { nameof(Website), "website" }
    };
}
