// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class ApplicationSet
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(ApplicationSetType), "applicationSetType" },
        { nameof(CreatedBy), "createdBy" },
        { nameof(Data), "data" },
        { nameof(Id), "id" },
        { nameof(Name), "name" }
    };
}
