// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class Archive
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(ArchivedDate), "archivedDate" },
        { nameof(IsArchived), "isArchived" }
    };
}
