// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class Assignee
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(AssigneeType), "assigneeType" },
        { nameof(Description), "description" },
        { nameof(Id), "id" },
        { nameof(NumberOfLinkedUsers), "numberOfLinkedUsers" }
    };
}
