// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class AttachmentOfEarnings
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Beneficiary), "beneficiary" },
        { nameof(Creditor), "creditor" },
        { nameof(Description1), "description1" },
        { nameof(Description2), "description2" },
        { nameof(DescriptionPayslip), "descriptionPayslip" },
        { nameof(EndDate), "endDate" },
        { nameof(FixedPaymentPerPayrollPeriod), "fixedPaymentPerPayrollPeriod" },
        { nameof(Iban), "iban" },
        { nameof(Id), "id" },
        { nameof(StartDate), "startDate" },
        { nameof(TotalAmount), "totalAmount" }
    };
}
