// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class AttachmentOfEarnings_beneficiary
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(City), "city" },
        { nameof(Name), "name" }
    };
}
