// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class AttachmentOfEarnings_creditor
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Priority), "priority" },
        { nameof(Type), "type" }
    };
}
