// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class AttachmentOfEarnings_totalAmount_paid
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(InApprovedPayrollRuns), "inApprovedPayrollRuns" },
        { nameof(InOpenPayrollRun), "inOpenPayrollRun" }
    };
}
