// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class AttachmentOfEarnings_totalAmount
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Owed), "owed" },
        { nameof(Paid), "paid" }
    };
}
