// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class AttachmentPostObject
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(File), "file" },
        { nameof(Filename), "filename" }
    };
}
