// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class AuditTrail_componentsSchemasEmployment
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Id), "id" },
        { nameof(StartDate), "startDate" }
    };
}
