// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class AuditTrailObject
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Attribute), "attribute" },
        { nameof(Category), "category" },
        { nameof(DateOfAlert), "dateOfAlert" },
        { nameof(Description), "description" },
        { nameof(EndUser), "endUser" },
        { nameof(Event), "event" },
        { nameof(EventDate), "eventDate" },
        { nameof(Role), "role" },
        { nameof(Year), "year" }
    };
}
