// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class AuthorizationsObject
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(CanWrite), "canWrite" },
        { nameof(Category), "category" },
        { nameof(IsAuthorizaionEditRestricted), "isAuthorizaionEditRestricted" },
        { nameof(IsTemplate), "isTemplate" }
    };
}
