// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class AuthorizationGroup
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(AuthorizationSet), "authorizationSet" },
        { nameof(Description), "description" },
        { nameof(Id), "id" },
        { nameof(IsLinked), "isLinked" },
        { nameof(NumberOfLinkedEmployers), "numberOfLinkedEmployers" },
        { nameof(NumberOfLinkedUsers), "numberOfLinkedUsers" }
    };
}
