// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class Authorization
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(AuthorizationSet), "authorizationSet" },
        { nameof(Authorizations), "authorizations" }
    };
}
