// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class AuthorizationsObject_canWrite
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(DepartmentManager), "departmentManager" },
        { nameof(Employee), "employee" },
        { nameof(Employer), "employer" },
        { nameof(Provider), "provider" }
    };
}
