// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class AutomaticPayrollDatePost_payrollPeriod
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(PeriodNumber), "periodNumber" }
    };
}
