// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class AvailableForEmployeePatch
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(AvailableForEmployeeDate), "availableForEmployeeDate" },
        { nameof(SendEmailToEmployee), "sendEmailToEmployee" }
    };
}
