// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class BasesForCalculationCollectivePatch
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(BaseForCalculationId), "baseForCalculationId" },
        { nameof(EmploymentId), "employmentId" },
        { nameof(EndDate), "endDate" }
    };
}
