// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class BasesForEmploymentFundCalculationBaseObject
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Base), "base" },
        { nameof(EndDate), "endDate" },
        { nameof(Id), "id" },
        { nameof(Origin), "origin" },
        { nameof(StartDate), "startDate" }
    };
}
