// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class BasesForCalculationCollectivePost_deviations
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(FinancialReservationPercentage), "financialReservationPercentage" },
        { nameof(Percentage), "percentage" },
        { nameof(ReservationPercentage), "reservationPercentage" }
    };
}
