// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class BenefitsAndDeductionsCollectivePost_payrollComponent
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Key), "key" }
    };
}
