// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class BenefitsAndDeductionsGetAndPut20180101
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(EndDate), "endDate" },
        { nameof(Id), "id" },
        { nameof(PayrollComponent), "payrollComponent" },
        { nameof(StartDate), "startDate" },
        { nameof(Value), "value" }
    };
}
