// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class BenefitPostGet
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Percentage), "percentage" },
        { nameof(Type), "type" }
    };
}
