// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class BenefitsAndDeductionsImportData
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(ClientNumber), "clientNumber" },
        { nameof(EmployeeNumber), "employeeNumber" },
        { nameof(FormattedName), "formattedName" },
        { nameof(PayrollComponentDescription), "payrollComponentDescription" },
        { nameof(PayrollComponentKey), "payrollComponentKey" },
        { nameof(PayrollEmployeeNumber), "payrollEmployeeNumber" },
        { nameof(StartDate), "startDate" },
        { nameof(Value), "value" }
    };
}
