// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class BenefitInKind_benefitInKindType
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Description), "description" },
        { nameof(Id), "id" }
    };
}
