// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class BenefitInKind
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(BenefitInKindType), "benefitInKindType" },
        { nameof(Brand), "brand" },
        { nameof(EndDate), "endDate" },
        { nameof(Id), "id" },
        { nameof(Particularities), "particularities" },
        { nameof(StartDate), "startDate" },
        { nameof(Supplier), "supplier" },
        { nameof(Type), "type" },
        { nameof(Value), "value" }
    };
}
