// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class BenifyObject
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Url), "url" }
    };
}
