// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class BillableItemEmployerObject_issuedTo_person
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(FirstName), "firstName" },
        { nameof(FormattedName), "formattedName" },
        { nameof(Id), "id" },
        { nameof(Initials), "initials" },
        { nameof(LastName), "lastName" },
        { nameof(LastNamePartner), "lastNamePartner" },
        { nameof(Prefix), "prefix" },
        { nameof(PrefixPartner), "prefixPartner" }
    };
}
