// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class BillableItemEmployerObject_requestedItem
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Id), "id" },
        { nameof(ItemType), "itemType" },
        { nameof(PreboardingTrajectory), "preboardingTrajectory" }
    };
}
