// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class BillableItemEmployerObject_employer
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(CompanyName), "companyName" },
        { nameof(Id), "id" }
    };
}
