// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class BillableItemEmployerObject_issuedTo
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Name), "name" },
        { nameof(Person), "person" }
    };
}
