// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class BillableItemProviderObject
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Employer), "employer" },
        { nameof(ItemType), "itemType" },
        { nameof(NumberOfBillableItems), "numberOfBillableItems" },
        { nameof(ProviderId), "providerId" }
    };
}
