// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class BillableItemProviderObject_employer
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(AdministrationNumber), "administrationNumber" },
        { nameof(CompanyName), "companyName" },
        { nameof(EmployerNumber), "employerNumber" },
        { nameof(Id), "id" }
    };
}
