// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class BillableItemEmployerObject_requestedItem_preboardingTrajectory
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(DateLastModification), "dateLastModification" },
        { nameof(Status), "status" }
    };
}
