// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class BillableItemEmployerObject
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Employer), "employer" },
        { nameof(Id), "id" },
        { nameof(IssuedTo), "issuedTo" },
        { nameof(ProviderId), "providerId" },
        { nameof(RequestedBy), "requestedBy" },
        { nameof(RequestedDate), "requestedDate" },
        { nameof(RequestedItem), "requestedItem" }
    };
}
