// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class CaseManager
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Function), "function" },
        { nameof(Name), "name" },
        { nameof(Organization), "organization" },
        { nameof(PhoneNumber), "phoneNumber" }
    };
}
