// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class ChangePersonalInformationRequest
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(CivilStatus), "civilStatus" },
        { nameof(Comment), "comment" },
        { nameof(EffectiveFromDate), "effectiveFromDate" },
        { nameof(HowToFormatLastName), "howToFormatLastName" },
        { nameof(LastNamePartner), "lastNamePartner" },
        { nameof(PrefixPartner), "prefixPartner" }
    };
}
