// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class ChangeIbanRequest
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Comment), "comment" },
        { nameof(Iban), "iban" }
    };
}
