// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class Child
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(DateOfBirth), "dateOfBirth" },
        { nameof(DateOfDeath), "dateOfDeath" },
        { nameof(FirstName), "firstName" },
        { nameof(Gender), "gender" },
        { nameof(Id), "id" },
        { nameof(Initials), "initials" },
        { nameof(LastName), "lastName" },
        { nameof(Prefix), "prefix" },
        { nameof(ResidenceStatus), "residenceStatus" }
    };
}
