// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class ClaData_collectiveLaborAgreement_baseForCalculation
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(BaseType), "baseType" },
        { nameof(Description), "description" },
        { nameof(Key), "key" },
        { nameof(Percentage), "percentage" },
        { nameof(ResultPayrollComponent), "resultPayrollComponent" }
    };
}
