// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class ClaData
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(CollectiveLaborAgreement), "collectiveLaborAgreement" }
    };
}
