// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class ClaData_collectiveLaborAgreement
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(BaseForCalculation), "baseForCalculation" },
        { nameof(Employments), "employments" },
        { nameof(Name), "name" },
        { nameof(NextYear), "nextYear" }
    };
}
