// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class ClaData_collectiveLaborAgreement_nextYear
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Available), "available" },
        { nameof(Status), "status" },
        { nameof(Year), "year" }
    };
}
