// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class ClaWageProjectionInput_payments
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Gross), "gross" },
        { nameof(Net), "net" }
    };
}
