// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class ClaWageProjectionInput_additionalPayrollPeriod
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Percentage), "percentage" },
        { nameof(ResultPayrollComponent), "resultPayrollComponent" }
    };
}
