// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class ClaWageProjectionInput_deviations
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(GrossWagePercentageChange), "grossWagePercentageChange" },
        { nameof(HoursPerWeek), "hoursPerWeek" }
    };
}
