// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class ClaWageProjectionInput_companyCar
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(FiscalAddition), "fiscalAddition" },
        { nameof(FiscalAdditionPeriod), "fiscalAdditionPeriod" }
    };
}
