// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class Client
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(AccessStatus), "accessStatus" },
        { nameof(ClientProp), "client" },
        { nameof(LastLogin), "lastLogin" }
    };
}
