// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class Client_client
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(ConsumerFriendlyName), "consumerFriendlyName" },
        { nameof(Id), "id" },
        { nameof(Name), "name" }
    };
}
