// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class CollectiveAction_itemCount
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Processed), "processed" },
        { nameof(ProcessedWithError), "processedWithError" },
        { nameof(ProcessedWithWarning), "processedWithWarning" },
        { nameof(Total), "total" }
    };
}
