// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class CollectiveActionDetail
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(CollectiveActionItemId), "collectiveActionItemId" },
        { nameof(CollectiveActionType), "collectiveActionType" },
        { nameof(CreatedOn), "createdOn" },
        { nameof(EmployerId), "employerId" },
        { nameof(EmploymentId), "employmentId" },
        { nameof(EntityId), "entityId" },
        { nameof(Messages), "messages" },
        { nameof(PayrollAdministrationId), "payrollAdministrationId" },
        { nameof(Succes), "succes" }
    };
}
