// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class ComponentsSchemasOrganizationalEntity
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Department), "department" },
        { nameof(DeviatingFunctionDescription), "deviatingFunctionDescription" },
        { nameof(DeviatingFunctionGroup), "deviatingFunctionGroup" },
        { nameof(DistributionUnit), "distributionUnit" },
        { nameof(Function), "function" },
        { nameof(InternalTelephoneExtensionNumber), "internalTelephoneExtensionNumber" },
        { nameof(PlaceOfEmployment), "placeOfEmployment" },
        { nameof(StandardFunction), "standardFunction" }
    };
}
