// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class ComponentsSchemasPayrollComponent
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(BalanceSheetSide), "balanceSheetSide" },
        { nameof(Category), "category" },
        { nameof(Description), "description" },
        { nameof(Key), "key" }
    };
}
