// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class ComponentsSchemasPayrollResults_employee
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(DateOfBirth), "dateOfBirth" },
        { nameof(EmployeeNumber), "employeeNumber" },
        { nameof(FormattedName), "formattedName" },
        { nameof(Gender), "gender" }
    };
}
