// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class ComponentsSchemasPayrollResults_employment_workinghours_shift
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(FullTimeHoursPerWeek), "fullTimeHoursPerWeek" }
    };
}
