// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class ComponentsSchemasPayrollResults_employment_workinghours
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(DeviatingHoursPerWeek), "deviatingHoursPerWeek" },
        { nameof(Shift), "shift" }
    };
}
