// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class ComponentsSchemasDocumentPutObject
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Attribute), "attribute" },
        { nameof(DateOfAlert), "dateOfAlert" },
        { nameof(Description), "description" },
        { nameof(QwoaterDocumentId), "qwoaterDocumentId" },
        { nameof(Year), "year" }
    };
}
