// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class ComponentsSchemasUserResponsibility
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(DeviatingHandler), "deviatingHandler" },
        { nameof(Id), "id" },
        { nameof(IsLinked), "isLinked" },
        { nameof(Name), "name" }
    };
}
