// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class ComponentsSchemasContactInformation
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(EmailAddress), "emailAddress" },
        { nameof(FaxNumber), "faxNumber" },
        { nameof(PhoneNumber), "phoneNumber" },
        { nameof(Website), "website" }
    };
}
