// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class ComponentsSchemasEmployer
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(CompanyName), "companyName" },
        { nameof(EmployerNumber), "employerNumber" },
        { nameof(Id), "id" }
    };
}
