// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class CompanyCar
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Brand), "brand" },
        { nameof(CatalogValue), "catalogValue" },
        { nameof(Comments), "comments" },
        { nameof(EndDate), "endDate" },
        { nameof(FuelCardNumber), "fuelCardNumber" },
        { nameof(Id), "id" },
        { nameof(KilometersPrivateUse), "kilometersPrivateUse" },
        { nameof(Lease), "lease" },
        { nameof(LeaseOrBuy), "leaseOrBuy" },
        { nameof(LicensePlateNumber), "licensePlateNumber" },
        { nameof(Model), "model" },
        { nameof(StartDate), "startDate" },
        { nameof(Supplier), "supplier" }
    };
}
