// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class ComponentsSchemasAddress
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(City), "city" },
        { nameof(Coordinates), "coordinates" },
        { nameof(HouseNumber), "houseNumber" },
        { nameof(PostalCode), "postalCode" },
        { nameof(Province), "province" },
        { nameof(Street), "street" }
    };
}
