// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class ComponentsSchemasEmployee
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(FirstName), "firstName" },
        { nameof(FormattedName), "formattedName" },
        { nameof(Id), "id" }
    };
}
