// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class ComponentsSchemasPayrollResults_employment
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(EndDate), "endDate" },
        { nameof(OrganizationalEntity), "organizationalEntity" },
        { nameof(PayrollId), "payrollId" },
        { nameof(StartDate), "startDate" },
        { nameof(Workinghours), "workinghours" }
    };
}
