// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class ComponentsSchemasPayrollResults_payrollAdministration
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(ClientNumber), "clientNumber" }
    };
}
