// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class ComponentsSchemasFiscal
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(AnnualSalary), "annualSalary" },
        { nameof(ApplyDayTables), "applyDayTables" },
        { nameof(ApplyDeviatingPayrollTaxPercentageOn), "applyDeviatingPayrollTaxPercentageOn" },
        { nameof(ApplyPayrollTaxDeduction), "applyPayrollTaxDeduction" },
        { nameof(ApplyStudentDeduction), "applyStudentDeduction" },
        { nameof(DeviatingCalculationRulePayrollTax), "deviatingCalculationRulePayrollTax" },
        { nameof(DeviatingPayrollTaxPercentage), "deviatingPayrollTaxPercentage" },
        { nameof(DeviatingPayrollTaxTableColour), "deviatingPayrollTaxTableColour" },
        { nameof(ResidentOf), "residentOf" }
    };
}
