// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class ComponentsSchemasPayrollResults_payrollResults
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(PayrollComponent), "payrollComponent" },
        { nameof(Value), "value" },
        { nameof(ValueSpecialTariff), "valueSpecialTariff" }
    };
}
