// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class ComponentsSchemasPayrollResults_employment_organizationalEntity
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Department), "department" },
        { nameof(DistributionUnit), "distributionUnit" },
        { nameof(Function), "function" }
    };
}
