// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class ComponentsSchemasPayrollResults_employment_organizationalEntity_department
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Code), "code" },
        { nameof(Description), "description" }
    };
}
