// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class CompanyCar_lease
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(ContractNumber), "contractNumber" },
        { nameof(EndDate), "endDate" },
        { nameof(StartDate), "startDate" }
    };
}
