// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class ComponentsSchemasPayrollResults
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Employee), "employee" },
        { nameof(Employer), "employer" },
        { nameof(Employment), "employment" },
        { nameof(PayrollAdministration), "payrollAdministration" },
        { nameof(PayrollPeriod), "payrollPeriod" },
        { nameof(PayrollResults), "payrollResults" }
    };
}
