// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class ConceptEmployeeContactPerson
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Address), "address" },
        { nameof(ContactRelationType), "contactRelationType" },
        { nameof(Description), "description" },
        { nameof(EmailAddress), "emailAddress" },
        { nameof(Id), "id" },
        { nameof(Name), "name" },
        { nameof(Particularities), "particularities" },
        { nameof(PhoneNumber), "phoneNumber" }
    };
}
