// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class ConceptEmployeeMinimized
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Address), "address" },
        { nameof(ApplyPayrollTaxDeduction), "applyPayrollTaxDeduction" },
        { nameof(ContactInformation), "contactInformation" },
        { nameof(Iban), "iban" },
        { nameof(Id), "id" },
        { nameof(IdentityDocument), "identityDocument" },
        { nameof(PersonalDetails), "personalDetails" }
    };
}
