// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class ConceptEmployee20180101
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(ConceptEmployeeStatus), "conceptEmployeeStatus" },
        { nameof(CreationDate), "creationDate" },
        { nameof(EmployeeData), "employeeData" },
        { nameof(EmploymentData), "employmentData" },
        { nameof(FiscalData), "fiscalData" },
        { nameof(Id), "id" },
        { nameof(OrganizationalEntityData), "organizationalEntityData" },
        { nameof(OtherPayrollVariablesData), "otherPayrollVariablesData" },
        { nameof(SelfService), "selfService" },
        { nameof(SocialSecurityData), "socialSecurityData" },
        { nameof(UniqueName), "uniqueName" },
        { nameof(WageData), "wageData" },
        { nameof(WorkingHoursData), "workingHoursData" }
    };
}
