// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class ConceptemployeeDetails
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(EmployeeNumber), "employeeNumber" },
        { nameof(FormattedName), "formattedName" },
        { nameof(Id), "id" },
        { nameof(Index), "index" }
    };
}
