// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class ConfigurationObject
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(DeviatingProviderLogo), "deviatingProviderLogo" }
    };
}
