// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class ConfiguredExternalTenantObject
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(ExternalTenant), "externalTenant" },
        { nameof(ExternalUser), "externalUser" }
    };
}
