// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class ConnectedApplicationPatch
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Code), "code" },
        { nameof(State), "state" }
    };
}
