// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class ConnectedApplicationInitiateRequest
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(ApplicationProvider), "applicationProvider" },
        { nameof(Description), "description" }
    };
}
