// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class ConnectedApplicationUrlResponse
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(AuthorizeUrl), "authorizeUrl" }
    };
}
