// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class ContactInformation20210329
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(BusinessEmailAddress), "businessEmailAddress" },
        { nameof(BusinessMobilePhoneNumber), "businessMobilePhoneNumber" },
        { nameof(BusinessPhoneNumber), "businessPhoneNumber" },
        { nameof(EmailAddress), "emailAddress" },
        { nameof(FaxNumber), "faxNumber" },
        { nameof(MobilePhoneNumber), "mobilePhoneNumber" },
        { nameof(PhoneNumber), "phoneNumber" }
    };
}
