// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class Contact
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Name), "name" },
        { nameof(PhoneNumber), "phoneNumber" }
    };
}
