// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class ContractExtensionRequest
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Comment), "comment" },
        { nameof(CommissionUntilDate), "commissionUntilDate" },
        { nameof(EmploymentDurationType), "employmentDurationType" },
        { nameof(StartDateContractOfIndefiniteDuration), "startDateContractOfIndefiniteDuration" }
    };
}
