// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class ContactHistory
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(ContactDate), "contactDate" },
        { nameof(ContactMethod), "contactMethod" },
        { nameof(Id), "id" },
        { nameof(Summary), "summary" }
    };
}
