// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class ContactInformation
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(City), "city" },
        { nameof(Country), "country" },
        { nameof(EndDate), "endDate" },
        { nameof(FurtherIndication), "furtherIndication" },
        { nameof(HouseNumber), "houseNumber" },
        { nameof(HouseNumberAddition), "houseNumberAddition" },
        { nameof(LocationType), "locationType" },
        { nameof(Name), "name" },
        { nameof(PhoneNumber), "phoneNumber" },
        { nameof(PostalCode), "postalCode" },
        { nameof(StartDate), "startDate" },
        { nameof(Street), "street" }
    };
}
