// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class CopyLeavePolicy
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Name), "name" },
        { nameof(SourceLeavePolicyId), "sourceLeavePolicyId" }
    };
}
