// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class CostCenterObject
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(AutomaticallyLinkToAllCostUnits), "automaticallyLinkToAllCostUnits" },
        { nameof(Code), "code" },
        { nameof(Description), "description" },
        { nameof(Id), "id" },
        { nameof(Origin), "origin" }
    };
}
