// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class CostPerHourPut_payrollPeriods
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(EndDate), "endDate" },
        { nameof(Id), "id" },
        { nameof(PeriodNumber), "periodNumber" },
        { nameof(StartDate), "startDate" },
        { nameof(Year), "year" }
    };
}
