// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class CostPerHour
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(CostPerHourProp), "costPerHour" },
        { nameof(Id), "id" },
        { nameof(PayrollPeriods), "payrollPeriods" },
        { nameof(RegistrationMethod), "registrationMethod" }
    };
}
