// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class CostUnitProviderLevelObject
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(AutomaticallyLinkToAllCostCenters), "automaticallyLinkToAllCostCenters" },
        { nameof(Code), "code" },
        { nameof(Description), "description" },
        { nameof(Id), "id" }
    };
}
