// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class Credentials
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Password), "password" },
        { nameof(Username), "username" }
    };
}
