// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class CurrentlyAvailableUnitsLeaveRequest
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(CurrentlyAvailableUnits), "currentlyAvailableUnits" },
        { nameof(Id), "id" }
    };
}
