// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class CustomNotifications
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(ExpirationDate), "expirationDate" },
        { nameof(Id), "id" },
        { nameof(NotificationDate), "notificationDate" },
        { nameof(NotificationText), "notificationText" },
        { nameof(RecurrencePattern), "recurrencePattern" }
    };
}
