// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class CustomNotifications_recurrencePattern
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(NumberOfRepetitionsAfterFirstNotification), "numberOfRepetitionsAfterFirstNotification" },
        { nameof(RecurrenceNumber), "recurrenceNumber" },
        { nameof(RecurrencePeriod), "recurrencePeriod" }
    };
}
