// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class DeclarationIds
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(DeclarationId), "declarationId" }
    };
}
