// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class DeclarationRequest
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(CalculatedDistanceByRoutingService), "calculatedDistanceByRoutingService" },
        { nameof(Comment), "comment" },
        { nameof(DeclarationDate), "declarationDate" },
        { nameof(NumberOfUnits), "numberOfUnits" },
        { nameof(PayrollComponent), "payrollComponent" },
        { nameof(ReasonForDeviatingFromCalculatedDistance), "reasonForDeviatingFromCalculatedDistance" },
        { nameof(Route), "route" }
    };
}
