// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class DeclarationObject_route_position
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Latitude), "latitude" },
        { nameof(Longitude), "longitude" }
    };
}
