// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class DeclarationsPatchObject
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Action), "action" },
        { nameof(Id), "id" }
    };
}
