// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class DeclarationsAuditTrail
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Comment), "comment" },
        { nameof(Id), "id" },
        { nameof(PerformedBy), "performedBy" },
        { nameof(PerformedOn), "performedOn" },
        { nameof(Status), "status" }
    };
}
