// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class DeclarationObject_payrollComponent
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(DeductionOrPayment), "deductionOrPayment" },
        { nameof(Description), "description" },
        { nameof(DeviatingDescription), "deviatingDescription" },
        { nameof(Key), "key" },
        { nameof(RouteType), "routeType" }
    };
}
