// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class DeclarationObject_route_pointOfInterest
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Name), "name" }
    };
}
