// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class DeclarationObject
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(CalculatedDistanceByRoutingService), "calculatedDistanceByRoutingService" },
        { nameof(DateOfLastChangeByEmployee), "dateOfLastChangeByEmployee" },
        { nameof(DateOfSubmissionByEmployee), "dateOfSubmissionByEmployee" },
        { nameof(DeclarationComment), "declarationComment" },
        { nameof(DeclarationDate), "declarationDate" },
        { nameof(DeclarationStatus), "declarationStatus" },
        { nameof(Id), "id" },
        { nameof(NumberOfUnits), "numberOfUnits" },
        { nameof(PayrollComponent), "payrollComponent" },
        { nameof(ProcessedInPayrollPeriod), "processedInPayrollPeriod" },
        { nameof(ReasonForDeviatingFromCalculatedDistance), "reasonForDeviatingFromCalculatedDistance" },
        { nameof(Route), "route" }
    };
}
