// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class DeclarationsProcessPatchObject
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Id), "id" },
        { nameof(PayrollPeriodId), "payrollPeriodId" }
    };
}
