// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class Defaults
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(CalculateUsingWorkPattern), "calculateUsingWorkPattern" },
        { nameof(EmploymentContractType), "employmentContractType" },
        { nameof(EmploymentDurationType), "employmentDurationType" },
        { nameof(GrossWageType), "grossWageType" },
        { nameof(MdvNotification), "mdvNotification" },
        { nameof(NetWageType), "netWageType" },
        { nameof(TypeOfEmployee), "typeOfEmployee" }
    };
}
