// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class Defaults_calculateUsingWorkPattern
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(DaysDailyRate), "daysDailyRate" },
        { nameof(DeviatingDaysAndHours), "deviatingDaysAndHours" },
        { nameof(HoursBrokenPeriod), "hoursBrokenPeriod" },
        { nameof(HoursRegularPeriod), "hoursRegularPeriod" }
    };
}
