// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class DeleteEmploymentInformation
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(HasDocument), "hasDocument" },
        { nameof(HasESSAndSingleEmployment), "hasESSAndSingleEmployment" },
        { nameof(HasEmployerUserEmployeeLink), "hasEmployerUserEmployeeLink" },
        { nameof(HasHealthInsuranceContract), "HasHealthInsuranceContract" },
        { nameof(HasMdvNotifications), "hasMdvNotifications" },
        { nameof(HasMeldingen), "hasMeldingen" },
        { nameof(HasMultipleEmployments), "hasMultipleEmployments" },
        { nameof(HasPayrollRunStatusOpen), "hasPayrollRunStatusOpen" },
        { nameof(HasWNLAndSingleEmployment), "hasWNLAndSingleEmployment" },
        { nameof(IsEmployed), "isEmployed" },
        { nameof(IsIncludedInApgPensionDeclaration), "isIncludedInApgPensionDeclaration" },
        { nameof(IsIncludedInPayroll), "isIncludedInPayroll" },
        { nameof(IsIncludedInPayrollTaxreturn), "isIncludedInPayrollTaxreturn" },
        { nameof(IsIncludedInPensionDeclaration), "isIncludedInPensionDeclaration" },
        { nameof(IsIncludedInUpaPensionDeclaration), "isIncludedInUpaPensionDeclaration" }
    };
}
