// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class DepartmentGetPostObject
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Archive), "archive" },
        { nameof(Code), "code" },
        { nameof(Description), "description" },
        { nameof(EmailLeaveRequest), "emailLeaveRequest" },
        { nameof(Id), "id" },
        { nameof(SubDepartmentOf), "subDepartmentOf" }
    };
}
