// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class DeviatingPostalAddress
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(City), "city" },
        { nameof(Country), "country" },
        { nameof(FurtherIndication), "furtherIndication" },
        { nameof(HouseNumber), "houseNumber" },
        { nameof(HouseNumberAddition), "houseNumberAddition" },
        { nameof(Location), "location" },
        { nameof(PoBox), "poBox" },
        { nameof(PostalCode), "postalCode" },
        { nameof(Street), "street" }
    };
}
