// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class Deviations
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(EmploymentContributionPercentage), "employmentContributionPercentage" },
        { nameof(TotalContributionPercentage), "totalContributionPercentage" }
    };
}
