// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class DeviatingAwfcontributions
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(EndPeriod), "endPeriod" },
        { nameof(Id), "id" },
        { nameof(StartPeriod), "startPeriod" },
        { nameof(TypeOfDeviatingAwfContribution), "typeOfDeviatingAwfContribution" }
    };
}
