// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class DnbObject
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(DataNewBusinessToken), "dataNewBusinessToken" },
        { nameof(ExpiresIn), "expiresIn" }
    };
}
