// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class DocumentSignObject
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(EmailAddress), "emailAddress" },
        { nameof(MobilePhoneNumber), "mobilePhoneNumber" },
        { nameof(Name), "name" },
        { nameof(SigningOrder), "signingOrder" }
    };
}
