// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class DocumentCountObject
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(NumberOfDocuments), "numberOfDocuments" }
    };
}
