// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class DocumentPutObject
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Attribute), "attribute" },
        { nameof(Category), "category" },
        { nameof(DateOfAlert), "dateOfAlert" },
        { nameof(DateOfSubmission), "dateOfSubmission" },
        { nameof(Description), "description" },
        { nameof(IsReadBy), "isReadBy" },
        { nameof(QwoaterDocumentId), "qwoaterDocumentId" },
        { nameof(SubmittedBy), "submittedBy" },
        { nameof(Year), "year" }
    };
}
