// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class DownloadRequest
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(DownloadRequestStatus), "downloadRequestStatus" },
        { nameof(ExpirationTime), "expirationTime" },
        { nameof(Filename), "filename" },
        { nameof(Id), "id" },
        { nameof(LatestDownloadTime), "latestDownloadTime" },
        { nameof(ProcessingFinishedTime), "processingFinishedTime" },
        { nameof(RequestTime), "requestTime" },
        { nameof(Year), "year" }
    };
}
