// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class EmailIdentity
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(DkimTokens), "dkimTokens" },
        { nameof(EmailIdentityProp), "emailIdentity" },
        { nameof(EmailIdentityType), "emailIdentityType" },
        { nameof(Id), "id" },
        { nameof(IsDkimVerified), "isDkimVerified" },
        { nameof(IsSpfVerified), "isSpfVerified" },
        { nameof(LastDkimVerifiedOn), "lastDkimVerifiedOn" },
        { nameof(LastSpfVerifiedOn), "lastSpfVerifiedOn" }
    };
}
