// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class EmailAddress
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(EmailAddressProp), "emailAddress" }
    };
}
