// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class EmailIdentityTestEmail
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(To), "to" }
    };
}
