// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class Employee
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Address), "address" },
        { nameof(ContactInformation), "contactInformation" },
        { nameof(DeviatingPostalAddress), "deviatingPostalAddress" },
        { nameof(EmployeeNumber), "employeeNumber" },
        { nameof(Iban), "iban" },
        { nameof(IdentityDocument), "identityDocument" },
        { nameof(PersonalDetails), "personalDetails" }
    };
}
