// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class EmployerUser_componentsSchemasContactInformation
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(EmailAddress), "emailAddress" },
        { nameof(PhoneNumber), "phoneNumber" },
        { nameof(PlaceOfEmployment), "placeOfEmployment" }
    };
}
