// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class Employee_personalDetails
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(CivilStatus), "civilStatus" },
        { nameof(DateOfBirth), "dateOfBirth" },
        { nameof(FirstName), "firstName" },
        { nameof(FormattedName), "formattedName" },
        { nameof(Gender), "gender" },
        { nameof(HowToFormatLastName), "howToFormatLastName" },
        { nameof(Initials), "initials" },
        { nameof(LastName), "lastName" },
        { nameof(LastNamePartner), "lastNamePartner" },
        { nameof(Nationality), "nationality" },
        { nameof(PlaceOfBirth), "placeOfBirth" },
        { nameof(Prefix), "prefix" },
        { nameof(PrefixPartner), "prefixPartner" },
        { nameof(Title), "title" }
    };
}
