// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class EmployeeSelfServicePatch
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Action), "action" },
        { nameof(EmployeeId), "employeeId" }
    };
}
