// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class EmployeeEducation
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(EducationLevel), "educationLevel" },
        { nameof(EmployeeCosts), "employeeCosts" },
        { nameof(EmployerCosts), "employerCosts" },
        { nameof(EndDate), "endDate" },
        { nameof(EndOfValidityDate), "endOfValidityDate" },
        { nameof(FurtherIndication), "furtherIndication" },
        { nameof(HasDiploma), "hasDiploma" },
        { nameof(Id), "id" },
        { nameof(Institute), "institute" },
        { nameof(Name), "name" },
        { nameof(Particularities), "particularities" },
        { nameof(StartDate), "startDate" },
        { nameof(TypeOfEducation), "typeOfEducation" },
        { nameof(YearOfDiploma), "yearOfDiploma" }
    };
}
