// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class Employee20210329
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Address), "address" },
        { nameof(ContactInformation), "contactInformation" },
        { nameof(DeviatingPostalAddress), "deviatingPostalAddress" },
        { nameof(EmployeeNumber), "employeeNumber" },
        { nameof(ExclusionFromAbsenceStatus), "exclusionFromAbsenceStatus" },
        { nameof(Id), "id" },
        { nameof(IdentityDocument), "identityDocument" },
        { nameof(PersonalDetails), "personalDetails" },
        { nameof(RevokeEmployeeSelfServiceAccessOn), "revokeEmployeeSelfServiceAccessOn" },
        { nameof(StatusEmployeeSelfService), "statusEmployeeSelfService" },
        { nameof(Travel), "travel" }
    };
}
