// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class EmployerCalendarLeaveRequest_calendar_details
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {

    };
}
