// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class EmploymentComprehensiveResponse20191216
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(BasesForCalculation), "basesForCalculation" },
        { nameof(BasesForEmploymentFundCalculation), "basesForEmploymentFundCalculation" },
        { nameof(BenefitsInKind), "benefitsInKind" },
        { nameof(CitizenServiceNumber), "citizenServiceNumber" },
        { nameof(CompanyCars), "companyCars" },
        { nameof(DeviatingAwfContribution), "deviatingAwfContribution" },
        { nameof(DeviatingHourlyWages), "deviatingHourlyWages" },
        { nameof(Employee), "employee" },
        { nameof(EmployeeCustomFields), "employeeCustomFields" },
        { nameof(Employment), "employment" },
        { nameof(EmploymentCustomFields), "employmentCustomFields" },
        { nameof(FiscalCompanyCars), "fiscalCompanyCars" },
        { nameof(FiscalProperties), "fiscalProperties" },
        { nameof(HealthcareInsuranceActConfiguration), "healthcareInsuranceActConfiguration" },
        { nameof(JournalAllocation), "journalAllocation" },
        { nameof(OrganizationalEntity), "organizationalEntity" },
        { nameof(OtherPayrollVariables), "otherPayrollVariables" },
        { nameof(PaymentInformationSepa), "paymentInformationSepa" },
        { nameof(PaymentinformationNonSepa), "paymentinformationNonSepa" },
        { nameof(PensionBenefits), "pensionBenefits" },
        { nameof(SocialSecurityBenefits), "socialSecurityBenefits" },
        { nameof(SocialSecurityConfiguration), "socialSecurityConfiguration" },
        { nameof(StatusEmployeeSelfService), "statusEmployeeSelfService" },
        { nameof(Wage), "wage" },
        { nameof(Workinghours), "workinghours" }
    };
}
