// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class EmploymentTemplates
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(EmploymentData), "employmentData" },
        { nameof(FiscalData), "fiscalData" },
        { nameof(Id), "id" },
        { nameof(OrganizationalEntityData), "organizationalEntityData" },
        { nameof(OtherPayrollVariablesData), "otherPayrollVariablesData" },
        { nameof(SocialSecurityData), "socialSecurityData" },
        { nameof(TemplateName), "templateName" },
        { nameof(WageData), "wageData" },
        { nameof(WorkingHoursData), "workingHoursData" }
    };
}
