// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class EmployeeAuditTrail
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Administration), "administration" },
        { nameof(Employee), "employee" },
        { nameof(Employer), "employer" },
        { nameof(Employment), "employment" },
        { nameof(Entity), "entity" },
        { nameof(Field), "field" },
        { nameof(Identification), "identification" },
        { nameof(MutationOrigin), "mutationOrigin" },
        { nameof(MutationType), "mutationType" },
        { nameof(NewValue), "newValue" },
        { nameof(OldValue), "oldValue" },
        { nameof(PerformedBy), "performedBy" },
        { nameof(TimeStamp), "timeStamp" }
    };
}
