// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class EmployerCalendarLeave_calendar
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Details), "details" },
        { nameof(EndDate), "endDate" },
        { nameof(StartDate), "startDate" }
    };
}
