// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class EmploymentDocumentRequestRequest
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Comment), "comment" },
        { nameof(DocumentType), "documentType" }
    };
}
