// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class EmployersObject
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(AdministrationNumber), "administrationNumber" },
        { nameof(CompanyName), "companyName" },
        { nameof(GroupCode), "groupCode" },
        { nameof(Id), "id" },
        { nameof(IsLinked), "isLinked" }
    };
}
