// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class Employment
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(CalculateWorkingHours), "calculateWorkingHours" },
        { nameof(CancellationNoticeDate), "cancellationNoticeDate" },
        { nameof(CancellationPeriodEmployee), "cancellationPeriodEmployee" },
        { nameof(CancellationPeriodEmployer), "cancellationPeriodEmployer" },
        { nameof(CancellationPeriodTimeUnit), "cancellationPeriodTimeUnit" },
        { nameof(CommissionUntilDate), "commissionUntilDate" },
        { nameof(DeviatingCLATaxReturn), "deviatingCLATaxReturn" },
        { nameof(EmailLeaveRequest), "emailLeaveRequest" },
        { nameof(EmployeeProfileId), "employeeProfileId" },
        { nameof(EmploymentContractType), "employmentContractType" },
        { nameof(EmploymentDurationType), "employmentDurationType" },
        { nameof(EssMutationSet), "essMutationSet" },
        { nameof(ExemptionInsuranceObligation), "exemptionInsuranceObligation" },
        { nameof(FirstDayNotification), "firstDayNotification" },
        { nameof(HasOnCallAppearanceObligation), "hasOnCallAppearanceObligation" },
        { nameof(HistoricalStartDate), "historicalStartDate" },
        { nameof(IncomeRelationshipNumber), "incomeRelationshipNumber" },
        { nameof(IsAnonymousEmployee), "isAnonymousEmployee" },
        { nameof(IsDirectorAndMajorShareholder), "isDirectorAndMajorShareholder" },
        { nameof(IsFamilyOfOwner), "isFamilyOfOwner" },
        { nameof(IsGemoedsbezwaardEmployeeInsurance), "isGemoedsbezwaardEmployeeInsurance" },
        { nameof(IsGemoedsbezwaardNationalInsurance), "isGemoedsbezwaardNationalInsurance" },
        { nameof(IsOnCallEmployment), "isOnCallEmployment" },
        { nameof(IsPreviousOwner), "isPreviousOwner" },
        { nameof(NamePayslip), "namePayslip" },
        { nameof(NonPayrollAdministration), "nonPayrollAdministration" },
        { nameof(Participation55plusRegulationUWV), "participation55plusRegulationUWV" },
        { nameof(PayrollAdministration), "payrollAdministration" },
        { nameof(PeriodPayGradeAdjustment), "periodPayGradeAdjustment" },
        { nameof(ProfessionCode), "professionCode" },
        { nameof(SendMdvNotification), "sendMdvNotification" },
        { nameof(SignalPayGradeAdjustment), "signalPayGradeAdjustment" },
        { nameof(SpecialIncomeRatio), "specialIncomeRatio" },
        { nameof(StartCancellationNoticePeriod), "startCancellationNoticePeriod" },
        { nameof(StartDate), "startDate" },
        { nameof(StartDateContractOfIndefiniteDuration), "startDateContractOfIndefiniteDuration" },
        { nameof(TypeOfEmployee), "typeOfEmployee" },
        { nameof(TypeOfParticipation), "typeOfParticipation" },
        { nameof(VacationCoupons), "vacationCoupons" },
        { nameof(ValueOfParticipation), "valueOfParticipation" },
        { nameof(WrittenEmploymentContract), "writtenEmploymentContract" }
    };
}
