// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class EmployeeBasic
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(DateOfBirth), "dateOfBirth" },
        { nameof(EmployeeNumber), "employeeNumber" },
        { nameof(FirstName), "firstName" },
        { nameof(FormattedName), "formattedName" },
        { nameof(Id), "id" },
        { nameof(Initials), "initials" },
        { nameof(LastName), "lastName" },
        { nameof(LastNamePartner), "lastNamePartner" },
        { nameof(Photo), "photo" },
        { nameof(Prefix), "prefix" },
        { nameof(PrefixPartner), "prefixPartner" }
    };
}
