// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class Employee20241113
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(CitizenServiceNumber), "citizenServiceNumber" },
        { nameof(EmployeeData), "employeeData" },
        { nameof(EmploymentData), "employmentData" },
        { nameof(FiscalData), "fiscalData" },
        { nameof(OrganizationalEntityData), "organizationalEntityData" },
        { nameof(OtherPayrollVariablesData), "otherPayrollVariablesData" },
        { nameof(SelfService), "selfService" },
        { nameof(SocialSecurityData), "socialSecurityData" },
        { nameof(WageData), "wageData" },
        { nameof(WorkingHoursData), "workingHoursData" }
    };
}
