// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class EmploymentFundsCollectivePatch
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(EmploymentFundId), "employmentFundId" },
        { nameof(EmploymentId), "employmentId" },
        { nameof(EndDate), "endDate" }
    };
}
