// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class EmploymentStartDate
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(StartDate), "startDate" }
    };
}
