// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class EmploymentMinimizedResponse20191216_employee
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(DateOfBirth), "dateOfBirth" },
        { nameof(EmployeeNumber), "employeeNumber" },
        { nameof(FirstName), "firstName" },
        { nameof(FormattedName), "formattedName" },
        { nameof(FullLastName), "fullLastName" },
        { nameof(Id), "id" },
        { nameof(Photo), "photo" }
    };
}
