// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class EmployeeProfileResponse
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(BasesForCalculation), "basesForCalculation" },
        { nameof(BenefitsAndDeductions), "benefitsAndDeductions" },
        { nameof(EmploymentFunds), "employmentFunds" },
        { nameof(EmploymentFundsABP), "employmentFundsABP" }
    };
}
