// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class EmploymentCategoryTypeFieldsObject
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(EmploymentCategoryType), "employmentCategoryType" },
        { nameof(LinkedEmployment), "linkedEmployment" }
    };
}
