// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class EmploymentMinimizedResponse20191216
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(CommissionUntilDate), "commissionUntilDate" },
        { nameof(Employee), "employee" },
        { nameof(EmploymentDurationType), "employmentDurationType" },
        { nameof(EndDate), "endDate" },
        { nameof(Id), "id" },
        { nameof(IncomeRelationshipNumber), "incomeRelationshipNumber" },
        { nameof(NonPayrollAdministration), "nonPayrollAdministration" },
        { nameof(PayrollAdministration), "payrollAdministration" },
        { nameof(PayrollId), "payrollId" },
        { nameof(StartDate), "startDate" }
    };
}
