// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class EmployeeEducation_institute
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(City), "city" },
        { nameof(Name), "Name" }
    };
}
