// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class Employee_contactInformation
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(EmailAddress), "emailAddress" },
        { nameof(FaxNumber), "faxNumber" },
        { nameof(MobilePhoneNumber), "mobilePhoneNumber" },
        { nameof(PhoneNumber), "phoneNumber" }
    };
}
