// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class EmploymentTermination20181231
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(CreateMdvEntry), "createMdvEntry" },
        { nameof(EndDate), "endDate" },
        { nameof(EndOfEmploymentDueToIllness), "endOfEmploymentDueToIllness" },
        { nameof(EndOfEmploymentReason), "endOfEmploymentReason" },
        { nameof(EndOfEmploymentReasonTaxAuthorities), "endOfEmploymentReasonTaxAuthorities" }
    };
}
