// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class EmployerCalendarLeave
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Calendar), "calendar" },
        { nameof(Department), "department" },
        { nameof(Employee), "employee" },
        { nameof(Employment), "employment" }
    };
}
