// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class Employee_identityDocument
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(DocumentIdentification), "documentIdentification" },
        { nameof(TypeOfDocument), "typeOfDocument" }
    };
}
