// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class EndOfAbsenceObject_endOfAbsence
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Date), "date" },
        { nameof(Reason), "reason" }
    };
}
