// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class EndOfAbsenceObject
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(EndOfAbsence), "endOfAbsence" }
    };
}
