// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class EntitlementMultiPatchObject
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(EmploymentId), "employmentId" },
        { nameof(IncludeStatutoryLeave), "includeStatutoryLeave" },
        { nameof(IncludeWtrLeave), "includeWtrLeave" },
        { nameof(LeavePolicyId), "leavePolicyId" },
        { nameof(Month), "month" },
        { nameof(Year), "year" }
    };
}
