// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class EntitlementMultiGetObject_leavePolicyEntitlement
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Entitlement), "entitlement" },
        { nameof(EntitlementAgeBasedLeave), "entitlementAgeBasedLeave" },
        { nameof(EntitlementWageBasedLeave), "entitlementWageBasedLeave" },
        { nameof(EntitlementYearsOfServiceBasedLeave), "entitlementYearsOfServiceBasedLeave" },
        { nameof(LeaveType), "leaveType" }
    };
}
