// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class EntitlementMultiGetObject
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Id), "id" },
        { nameof(LeavePolicyEntitlement), "leavePolicyEntitlement" }
    };
}
