// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class EssAccessMigration_employee
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(EmailAddress), "emailAddress" },
        { nameof(EmployeeNumber), "employeeNumber" },
        { nameof(EmploymentEndDate), "employmentEndDate" },
        { nameof(FirstName), "firstName" },
        { nameof(FormattedName), "formattedName" },
        { nameof(Id), "id" }
    };
}
