// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class EssAccessClever
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(EmployeeId), "employeeId" },
        { nameof(Status), "status" }
    };
}
