// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class EssAccessConceptEmployee_conceptEmployee
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(EmailAddress), "emailAddress" },
        { nameof(EmployeeNumber), "employeeNumber" },
        { nameof(FirstName), "firstName" },
        { nameof(FormattedName), "formattedName" },
        { nameof(Id), "id" },
        { nameof(Initials), "initials" },
        { nameof(LastName), "lastName" },
        { nameof(Prefix), "prefix" }
    };
}
