// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class EssAccessWithoutEmployee
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(HasTwoFactorAuthentication), "hasTwoFactorAuthentication" },
        { nameof(Status), "status" }
    };
}
