// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class EssAccessConceptEmployee
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(ConceptEmployee), "conceptEmployee" },
        { nameof(Status), "status" }
    };
}
