// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class EssAccessMigration
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Employee), "employee" },
        { nameof(StatusESS), "statusESS" },
        { nameof(StatusWNL), "statusWNL" }
    };
}
