// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class EventNotification
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Category), "category" },
        { nameof(DefinedAtLevel), "definedAtLevel" },
        { nameof(DependsOnModule), "dependsOnModule" },
        { nameof(EmailAddress), "emailAddress" },
        { nameof(Type), "type" }
    };
}
