// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class FinancialAdministration
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Code), "code" },
        { nameof(ExternalValue), "externalValue" }
    };
}
