// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class FiscalCompanyCar_reasonForNoAdditionalTaxLiability
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Key), "key" },
        { nameof(Value), "value" }
    };
}
