// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class FiscalCompanyCar
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(AdditionalTaxLiabilityGroup), "additionalTaxLiabilityGroup" },
        { nameof(DateOfFirstAdmission), "dateOfFirstAdmission" },
        { nameof(DeviatingAdditionalTaxLiability), "deviatingAdditionalTaxLiability" },
        { nameof(EndDate), "endDate" },
        { nameof(Id), "id" },
        { nameof(LicensePlateNumber), "licensePlateNumber" },
        { nameof(ReasonForNoAdditionalTaxLiability), "reasonForNoAdditionalTaxLiability" },
        { nameof(StartDate), "startDate" },
        { nameof(TaxableBenefitForPrivateUse), "taxableBenefitForPrivateUse" },
        { nameof(ValueForTaxPurposes), "valueForTaxPurposes" }
    };
}
