// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class FiscalPropertiesCollective
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(AnnualSalary), "annualSalary" },
        { nameof(EmploymentId), "employmentId" },
        { nameof(StartDate), "startDate" }
    };
}
