// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class FixedContribution
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(EmploymentContribution), "employmentContribution" },
        { nameof(TotalContribution), "totalContribution" }
    };
}
