// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class GenerateDocument_componentsSchemasDocumentPostObject
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Attribute), "attribute" },
        { nameof(DateOfAlert), "dateOfAlert" },
        { nameof(Description), "description" },
        { nameof(Filename), "filename" },
        { nameof(ReferenceDate), "referenceDate" },
        { nameof(TemplateEmployerId), "templateEmployerId" },
        { nameof(Year), "year" }
    };
}
