// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class HealthcareInsuranceActConfiguration
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(AdditionalContributionEmployer), "additionalContributionEmployer" },
        { nameof(AdditionalPremium), "additionalPremium" },
        { nameof(EndDate), "endDate" },
        { nameof(HealthcareInsuranceActType), "healthcareInsuranceActType" },
        { nameof(Id), "id" },
        { nameof(NominalPremium), "nominalPremium" },
        { nameof(StartDate), "startDate" }
    };
}
