// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class IdealStatus
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(LastStatusRequest), "lastStatusRequest" },
        { nameof(Status), "status" }
    };
}
