// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class IdealStatus_status
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Code), "code" },
        { nameof(Reason), "reason" }
    };
}
