// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class Ideal401Error
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(MessageEscaped), "message" }
    };
}
