// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class Identification
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Description), "description" }
    };
}
