// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class ImportFile
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Data), "data" },
        { nameof(MimeType), "mimeType" }
    };
}
