// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class InitializeProforma
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(EmployeeId), "employeeId" },
        { nameof(ProformaType), "proformaType" }
    };
}
