// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class InitiationParametersNew
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(NotifyOfInitiation), "notifyOfInitiation" },
        { nameof(PayrollPeriod), "payrollPeriod" }
    };
}
