// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class InitiationParametersPensionDeclaration
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(PayrollPeriod), "payrollPeriod" }
    };
}
