// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class InitiationParametersForPreviousPayrollYear
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(NotifyOfInitiation), "notifyOfInitiation" },
        { nameof(PayrollYear), "payrollYear" }
    };
}
