// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class InitiationParameters
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(NotifyOfInitiation), "notifyOfInitiation" }
    };
}
