// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class InitiationParametersPensionDeclaration_payrollPeriod
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(PeriodNumber), "periodNumber" },
        { nameof(Year), "year" }
    };
}
