// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class InputParameters
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(BaseCalculationsBonusPercentage), "baseCalculationsBonusPercentage" },
        { nameof(EndDate), "endDate" },
        { nameof(GrossMonthlySupplement), "grossMonthlySupplement" },
        { nameof(GrossMonthlyWage), "grossMonthlyWage" },
        { nameof(ShiftBonusPercentage), "shiftBonusPercentage" },
        { nameof(StartDate), "startDate" }
    };
}
