// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class InsuranceContract
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(BelongsToEmployerId), "belongsToEmployerId" },
        { nameof(ContractNumber), "contractNumber" },
        { nameof(EndDate), "endDate" },
        { nameof(Id), "id" },
        { nameof(StartDate), "startDate" }
    };
}
