// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class Integration_application
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Id), "id" },
        { nameof(IsAvailableInMarketplace), "isAvailableInMarketplace" },
        { nameof(IsBlocked), "isBlocked" },
        { nameof(Logo), "logo" },
        { nameof(Name), "name" }
    };
}
