// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class Integration
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Application), "application" },
        { nameof(CreatedOn), "createdOn" },
        { nameof(IsBlocked), "isBlocked" },
        { nameof(LastLogin), "lastLogin" }
    };
}
