// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class JournalProfileObject_origin
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Description), "description" },
        { nameof(Key), "key" }
    };
}
