// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class JournalAllocationObject
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(AllocationBasedOnActualHours), "allocationBasedOnActualHours" },
        { nameof(AllocationBasedOnFixedWeights), "allocationBasedOnFixedWeights" },
        { nameof(EndPeriod), "endPeriod" },
        { nameof(Id), "id" },
        { nameof(JournalProfileConfiguration), "journalProfileConfiguration" },
        { nameof(StartPeriod), "startPeriod" }
    };
}
