// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class JournalAllocationObject_journalProfileConfiguration
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(EndPeriod), "endPeriod" },
        { nameof(Id), "id" },
        { nameof(JournalProfile), "journalProfile" },
        { nameof(StartPeriod), "startPeriod" }
    };
}
