// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class JournalRunExportAuditTrail
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(ExportStatus), "exportStatus" },
        { nameof(ExportedBy), "exportedBy" },
        { nameof(ExportedOn), "exportedOn" },
        { nameof(ExportedTo), "exportedTo" },
        { nameof(Id), "id" },
        { nameof(MethodOfExporting), "methodOfExporting" },
        { nameof(ReturendErrorMessage), "returendErrorMessage" },
        { nameof(SequenceNumber), "sequenceNumber" }
    };
}
