// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class JournalRunError
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(CostCenter), "costCenter" },
        { nameof(CostUnit), "costUnit" },
        { nameof(Error), "error" },
        { nameof(GeneralLedgerAccount), "generalLedgerAccount" },
        { nameof(Id), "id" },
        { nameof(PayrollComponent), "payrollComponent" },
        { nameof(PayrollEmployeeNumber), "PayrollEmployeeNumber" }
    };
}
