// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class JournalAllocationObject_allocationBasedOnActualHours
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(CostCenter), "costCenter" },
        { nameof(CostUnit), "costUnit" }
    };
}
