// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class JournalrunExportSend_subAdministration
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Id), "Id" },
        { nameof(Name), "Name" }
    };
}
