// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class JournalProfileObject
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Description), "description" },
        { nameof(Id), "id" },
        { nameof(Key), "key" },
        { nameof(Origin), "origin" }
    };
}
