// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class JournalrunExportDownload
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Date), "date" },
        { nameof(IncludeCostCenter), "includeCostCenter" },
        { nameof(IncludeCostUnit), "includeCostUnit" },
        { nameof(SuspenseAccount), "suspenseAccount" }
    };
}
