// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class JournalProfilePostObject
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Description), "description" },
        { nameof(JournalProfileIdToCopy), "journalProfileIdToCopy" }
    };
}
