// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class JournalProfileProviderLevelObject
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Description), "description" },
        { nameof(Id), "id" },
        { nameof(NumberOfActiveAdministrations), "numberOfActiveAdministrations" },
        { nameof(NumberOfHistoricAdministrations), "numberOfHistoricAdministrations" }
    };
}
