// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class JournalRun
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Id), "id" },
        { nameof(JournalRunStatus), "journalRunStatus" },
        { nameof(MethodOfCreation), "methodOfCreation" },
        { nameof(PayrollRun), "payrollRun" },
        { nameof(ProcessingFinishedTime), "processingFinishedTime" },
        { nameof(RemoveTime), "removeTime" },
        { nameof(RemovedBy), "removedBy" },
        { nameof(RequestTime), "requestTime" },
        { nameof(RequestedBy), "requestedBy" },
        { nameof(SequenceNumber), "sequenceNumber" }
    };
}
