// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class JournalrunExportSend
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Account), "account" },
        { nameof(AccountKey), "accountKey" },
        { nameof(Administration), "administration" },
        { nameof(Date), "date" },
        { nameof(Description), "description" },
        { nameof(DeviatingJournalSeries), "deviatingJournalSeries" },
        { nameof(FinancialYear), "financialYear" },
        { nameof(IncludeCostCenter), "includeCostCenter" },
        { nameof(IncludeCostUnit), "includeCostUnit" },
        { nameof(JournalCode), "journalCode" },
        { nameof(JournalNumber), "journalNumber" },
        { nameof(LinkCostCenterToGroup), "linkCostCenterToGroup" },
        { nameof(LinkCostUnitToGroup), "linkCostUnitToGroup" },
        { nameof(Period), "period" },
        { nameof(SubAdministration), "subAdministration" },
        { nameof(SuspenseAccount), "suspenseAccount" },
        { nameof(User), "user" }
    };
}
