// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class JournalRun_payrollRun
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(PayrollPeriod), "payrollPeriod" },
        { nameof(PayrollRunId), "payrollRunId" },
        { nameof(SequenceNumberApproved), "sequenceNumberApproved" }
    };
}
