// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class JournalrunStatusPatch
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Action), "action" },
        { nameof(Application), "application" },
        { nameof(Message), "message" }
    };
}
