// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class JournalrunExportSend_administration
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Id), "id" },
        { nameof(Value), "value" }
    };
}
