// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class JournalRunCumulativeResults
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(CostCenter), "costCenter" },
        { nameof(CostUnit), "costUnit" },
        { nameof(CreditAmount), "creditAmount" },
        { nameof(DebetAmount), "debetAmount" },
        { nameof(GeneralLedgerAccount), "generalLedgerAccount" },
        { nameof(PayrollComponent), "payrollComponent" },
        { nameof(PayrollPeriodEnd), "payrollPeriodEnd" },
        { nameof(PayrollPeriodStart), "payrollPeriodStart" }
    };
}
