// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class LeaveCalendar
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Dates), "dates" },
        { nameof(EmployeeName), "employeeName" },
        { nameof(EmploymentId), "employmentId" },
        { nameof(Leave), "leave" }
    };
}
