// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class LeavePolicy_leaveRequest
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(ApplyLeaveSchedule), "applyLeaveSchedule" },
        { nameof(LeavePattern), "leavePattern" },
        { nameof(UseHolidaysInCalculation), "useHolidaysInCalculation" }
    };
}
