// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class LeavePolicy_leaveRequest_leavePattern_evenWeeks
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Friday), "friday" },
        { nameof(Monday), "monday" },
        { nameof(Saturday), "saturday" },
        { nameof(Sunday), "sunday" },
        { nameof(Thursday), "thursday" },
        { nameof(Tuesday), "tuesday" },
        { nameof(Wednesday), "wednesday" }
    };
}
