// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class LeaveImportData
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(EmployeeNumber), "employeeNumber" },
        { nameof(EmployerNumber), "employerNumber" },
        { nameof(EndDate), "endDate" },
        { nameof(FormattedName), "formattedName" },
        { nameof(IsAccrual), "isAccrual" },
        { nameof(LeaveTypeKey), "leaveTypeKey" },
        { nameof(NumberOfUnits), "numberOfUnits" },
        { nameof(PayrollEmployeeNumber), "payrollEmployeeNumber" },
        { nameof(StartDate), "startDate" }
    };
}
