// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class LeaveBalance
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Accrual), "accrual" },
        { nameof(Balance), "balance" },
        { nameof(BalancePreviousYear), "balancePreviousYear" },
        { nameof(Expires), "expires" },
        { nameof(LeaveType), "leaveType" },
        { nameof(UnitType), "unitType" },
        { nameof(UsageAfterToday), "usageAfterToday" },
        { nameof(UsageFirstHalfYear), "usageFirstHalfYear" },
        { nameof(UsageThroughToday), "usageThroughToday" },
        { nameof(UsageTotal), "usageTotal" },
        { nameof(Year), "year" }
    };
}
