// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class LeaveBalanceEmployerGroupedBy
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Groups), "groups" },
        { nameof(Totals), "totals" }
    };
}
