// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class LeavePolicy_leaveEntitlement
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(ExcessLeaveToStatutory), "excessLeaveToStatutory" },
        { nameof(Statutory), "statutory" },
        { nameof(Wtr), "wtr" }
    };
}
