// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class LeavePolicyAccrual
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Id), "id" },
        { nameof(LeavePolicyAccrualProp), "leavePolicyAccrual" }
    };
}
