// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class LeaveBalanceEmployerWithWorth_leaveBalance
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Accrual), "accrual" },
        { nameof(Balance), "balance" },
        { nameof(BalancePreviousYear), "balancePreviousYear" },
        { nameof(Expires), "expires" },
        { nameof(LeaveType), "leaveType" },
        { nameof(UsageAfterReferenceDate), "usageAfterReferenceDate" },
        { nameof(UsageFirstHalfYear), "usageFirstHalfYear" },
        { nameof(UsageThroughReferenceDate), "usageThroughReferenceDate" },
        { nameof(UsageTotal), "usageTotal" },
        { nameof(Worth), "worth" },
        { nameof(Year), "year" }
    };
}
