// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class LeavePolicy
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(AccrualType), "accrualType" },
        { nameof(AdditionalLeave), "additionalLeave" },
        { nameof(DayOfTheMonthToPerformAutomaticLeaveCalculationOn), "dayOfTheMonthToPerformAutomaticLeaveCalculationOn" },
        { nameof(Id), "id" },
        { nameof(LeaveEntitlement), "leaveEntitlement" },
        { nameof(LeaveRequest), "leaveRequest" },
        { nameof(LeaveUnitType), "leaveUnitType" },
        { nameof(Name), "name" },
        { nameof(PayoutLeaveImmediately), "payoutLeaveImmediately" },
        { nameof(RoundTo), "roundTo" },
        { nameof(RoundingMethod), "roundingMethod" }
    };
}
