// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class LeaveBalanceEmployerGroupedBy_groups
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Accrual), "accrual" },
        { nameof(Balance), "balance" },
        { nameof(BalancePreviousYear), "balancePreviousYear" },
        { nameof(Group), "group" },
        { nameof(LeaveType), "leaveType" },
        { nameof(UsageAfterReferenceDate), "usageAfterReferenceDate" },
        { nameof(UsageThroughReferenceDate), "usageThroughReferenceDate" },
        { nameof(UsageTotal), "usageTotal" },
        { nameof(Year), "year" }
    };
}
