// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class LeaveBalanceEmployerWithWorth
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Employee), "employee" },
        { nameof(EndDate), "endDate" },
        { nameof(HistoricalStartDate), "historicalStartDate" },
        { nameof(Id), "id" },
        { nameof(IncomeRelationshipNumber), "incomeRelationshipNumber" },
        { nameof(LeaveBalance), "leaveBalance" },
        { nameof(NonPayrollAdministration), "nonPayrollAdministration" },
        { nameof(OrganizationalEntity), "organizationalEntity" },
        { nameof(PayrollAdministration), "payrollAdministration" },
        { nameof(StartDate), "startDate" }
    };
}
