// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class LeaveRequest
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(CommentEmployee), "commentEmployee" },
        { nameof(CommentHandler), "commentHandler" },
        { nameof(CurrentlyAvailableUnits), "currentlyAvailableUnits" },
        { nameof(EndDate), "endDate" },
        { nameof(HandledBy), "handledBy" },
        { nameof(HandledTime), "handledTime" },
        { nameof(Id), "id" },
        { nameof(IsAccrual), "isAccrual" },
        { nameof(LeaveRequestStatus), "leaveRequestStatus" },
        { nameof(LeaveType), "leaveType" },
        { nameof(NumberOfUnits), "numberOfUnits" },
        { nameof(StartDate), "startDate" },
        { nameof(StartedViaWorkflow), "startedViaWorkflow" },
        { nameof(SubmittedBy), "submittedBy" },
        { nameof(SubmittedOn), "submittedOn" },
        { nameof(UnitType), "unitType" }
    };
}
