// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class LeavePolicy_additionalLeave
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(AllocationType), "allocationType" },
        { nameof(ReferenceDate1), "referenceDate1" },
        { nameof(ReferenceDate2), "referenceDate2" }
    };
}
