// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class LeavePolicy_additionalLeave_referenceDate1
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Day), "day" },
        { nameof(Month), "month" }
    };
}
