// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class LeaveCalendar_leave
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(EndDate), "endDate" },
        { nameof(StartDate), "startDate" },
        { nameof(Status), "status" }
    };
}
