// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class LeaveCalendar_dates
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Date), "date" },
        { nameof(LeaveStatus), "leaveStatus" },
        { nameof(NoAccess), "noAccess" },
        { nameof(NonWorkday), "nonWorkday" }
    };
}
