// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class LedgerAccountToPayrollComponentLinkObjectGetAndPatch
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(CostCenter), "costCenter" },
        { nameof(CostUnit), "costUnit" },
        { nameof(Id), "id" },
        { nameof(LedgerAccount), "ledgerAccount" },
        { nameof(Origin), "origin" },
        { nameof(PayrollComponent), "payrollComponent" }
    };
}
