// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class LedgerAccountToPayrollComponentLinkObjectMetadata_options
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {

    };
}
