// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class LedgerAccountToPayrollComponentLinkObjectMetadata
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Field), "field" },
        { nameof(Options), "options" }
    };
}
