// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class LedgerAccountProviderLevelObject
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Consolidate), "consolidate" },
        { nameof(CostAccount), "costAccount" },
        { nameof(Description), "description" },
        { nameof(Id), "id" },
        { nameof(Number), "number" }
    };
}
