// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class Licenses
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(License), "license" }
    };
}
