// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class Licenses_license
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(User), "user" }
    };
}
