// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class LinkedDepartments_personalDetails
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(FirstName), "firstName" },
        { nameof(Initials), "initials" },
        { nameof(LastName), "lastName" },
        { nameof(Prefix), "prefix" }
    };
}
