// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class LinkExistingUser
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Departments), "departments" },
        { nameof(UserId), "userId" }
    };
}
