// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class LinkedEmployeePatch
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(EmployeeId), "employeeId" }
    };
}
