// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class LinkedDepartmentsPatch
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Action), "action" },
        { nameof(DepartmentId), "departmentId" },
        { nameof(HasAccessToSubDepartments), "hasAccessToSubDepartments" }
    };
}
