// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class LinkedUsersPatch
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(DeviatingHandlerId), "deviatingHandlerId" },
        { nameof(Id), "id" },
        { nameof(IsLinked), "isLinked" }
    };
}
