// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class LinkedDepartments
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Departments), "departments" },
        { nameof(PersonalDetails), "personalDetails" },
        { nameof(UserId), "userId" }
    };
}
