// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class LogoObjectList
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Attribute), "attribute" },
        { nameof(Id), "id" },
        { nameof(Name), "name" },
        { nameof(Url), "url" }
    };
}
