// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class MatrixObject
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(CostCenter), "costCenter" },
        { nameof(CostUnit), "costUnit" },
        { nameof(Linked), "linked" },
        { nameof(Locked), "locked" }
    };
}
