// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class MdvMeldingen_employment
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(ClaExternalParty), "claExternalParty" },
        { nameof(EndDate), "endDate" },
        { nameof(StartDate), "startDate" }
    };
}
