// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class MdvMeldingen_employee
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(CitizenServiceNumber), "citizenServiceNumber" },
        { nameof(DateOfBirth), "dateOfBirth" },
        { nameof(Gender), "gender" },
        { nameof(Initials), "initials" },
        { nameof(LastName), "lastName" },
        { nameof(Prefix), "prefix" }
    };
}
