// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class MdvMeldingen_payrollAdministration
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(PayrollTaxesNumber), "payrollTaxesNumber" }
    };
}
