// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class MdvMeldingen
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Employee), "employee" },
        { nameof(Employment), "employment" },
        { nameof(PayrollAdministration), "payrollAdministration" }
    };
}
