// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class ModulesEmployersReport
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Employer), "employer" },
        { nameof(ModuleSet), "moduleSet" },
        { nameof(Modules), "modules" },
        { nameof(PayrollAdministration), "payrollAdministration" },
        { nameof(UserHasAccess), "userHasAccess" }
    };
}
