// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class ModulesEmployersReport_modules
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Description), "description" },
        { nameof(Id), "id" },
        { nameof(IsEnabled), "isEnabled" },
        { nameof(Number), "number" }
    };
}
