// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class ModuleSetPatch
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Description), "description" },
        { nameof(Modules), "modules" }
    };
}
