// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class NationalHoliday_deviations
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Enabled), "enabled" },
        { nameof(Value), "value" }
    };
}
