// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class NonPayrollAdministration
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Cao), "cao" },
        { nameof(Description), "description" },
        { nameof(EndDate), "endDate" },
        { nameof(FulltimeHours), "fulltimeHours" },
        { nameof(HolidayAllowanceBaseForCalculation), "holidayAllowanceBaseForCalculation" },
        { nameof(HolidayAllowancePercentage), "holidayAllowancePercentage" },
        { nameof(Id), "id" },
        { nameof(PayrollPeriodType), "payrollPeriodType" },
        { nameof(StartDate), "startDate" },
        { nameof(YearEndBaseForCalculation), "yearEndBaseForCalculation" },
        { nameof(YearEndPercentage), "yearEndPercentage" }
    };
}
