// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class NotesByPayrollAdministration_concerningPayrollRun
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(ApprovalTime), "approvalTime" },
        { nameof(Id), "id" },
        { nameof(PayrollPeriod), "payrollPeriod" },
        { nameof(ProcessingFinishedTime), "processingFinishedTime" },
        { nameof(SequenceNumber), "sequenceNumber" }
    };
}
