// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class NotesByPayrollAdministration
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(AccessibleBy), "accessibleBy" },
        { nameof(ConcerningPayrollRun), "concerningPayrollRun" },
        { nameof(CreatedBy), "createdBy" },
        { nameof(CreatedOn), "createdOn" },
        { nameof(Id), "id" },
        { nameof(LastModifiedBy), "lastModifiedBy" },
        { nameof(LastModifiedOn), "lastModifiedOn" },
        { nameof(Note), "note" },
        { nameof(Subject), "subject" }
    };
}
