// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class NotificationSummary
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(EmployerId), "employerId" },
        { nameof(NumberOfUnreadNotifications), "numberOfUnreadNotifications" }
    };
}
