// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class NotificationSetPatch
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Description), "description" },
        { nameof(Notifications), "notifications" }
    };
}
