// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class NotificationProvider
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(AppliesToEmployee), "appliesToEmployee" },
        { nameof(Employer), "employer" },
        { nameof(EmployerId), "employerId" },
        { nameof(EmployerLogo), "employerLogo" },
        { nameof(EmployerName), "employerName" },
        { nameof(Id), "id" },
        { nameof(IsRead), "isRead" },
        { nameof(MarkedAsReadBy), "markedAsReadBy" },
        { nameof(MarkedAsReadOn), "markedAsReadOn" },
        { nameof(NonPayrollAdministration), "nonPayrollAdministration" },
        { nameof(NotificationDate), "notificationDate" },
        { nameof(NotificationType), "notificationType" },
        { nameof(NotificationTypeClarification), "notificationTypeClarification" },
        { nameof(PayrollAdministration), "payrollAdministration" }
    };
}
