// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class Notification
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(AppliesToEmployee), "appliesToEmployee" },
        { nameof(AppliesToEmployment), "appliesToEmployment" },
        { nameof(Id), "id" },
        { nameof(IsRead), "isRead" },
        { nameof(MarkedAsReadBy), "markedAsReadBy" },
        { nameof(MarkedAsReadOn), "markedAsReadOn" },
        { nameof(NotificationDate), "notificationDate" },
        { nameof(NotificationType), "notificationType" },
        { nameof(NotificationTypeClarification), "notificationTypeClarification" }
    };
}
