// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class OccupationalDisability
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Classification), "classification" },
        { nameof(EndDate), "endDate" },
        { nameof(Id), "id" },
        { nameof(IsExWAO), "isExWAO" },
        { nameof(IsOccupationallyDisabled), "isOccupationallyDisabled" },
        { nameof(StartDate), "startDate" }
    };
}
