// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class OtherPayrollVariables
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(DeviatingPremiumGroup), "deviatingPremiumGroup" }
    };
}
