// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class OutputParameters
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(EmploymentDurationInDecimalYears), "employmentDurationInDecimalYears" },
        { nameof(MonthlyWage), "monthlyWage" },
        { nameof(TransitionCompensationAmount), "transitionCompensationAmount" }
    };
}
