// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class Partner
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(DateOfBirth), "dateOfBirth" },
        { nameof(DateOfDeath), "dateOfDeath" },
        { nameof(EndDate), "endDate" },
        { nameof(FirstName), "firstName" },
        { nameof(Gender), "gender" },
        { nameof(HowToFormatLastName), "howToFormatLastName" },
        { nameof(Id), "id" },
        { nameof(Initials), "initials" },
        { nameof(LastName), "lastName" },
        { nameof(PlaceOfBirth), "placeOfBirth" },
        { nameof(Prefix), "prefix" },
        { nameof(StartDate), "startDate" },
        { nameof(Title), "title" },
        { nameof(WaoClassification), "waoClassification" }
    };
}
