// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class PatchResponse
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Failed), "failed" },
        { nameof(Successfull), "successfull" }
    };
}
