// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class PatchUserInvite_resendInformation
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(DestinationForSecret), "destinationForSecret" },
        { nameof(EmailAddress), "emailAddress" },
        { nameof(ProviderId), "providerId" },
        { nameof(TwoFactorAuthenticationRequired), "twoFactorAuthenticationRequired" }
    };
}
