// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class PawwDeclaration_responseMessages
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(CitizenServiceNumber), "citizenServiceNumber" },
        { nameof(Code), "code" },
        { nameof(DatetimeOfMessageReceipt), "datetimeOfMessageReceipt" },
        { nameof(DatetimeOfRegistration), "datetimeOfRegistration" },
        { nameof(Description), "description" },
        { nameof(DescriptionFragment), "descriptionFragment" },
        { nameof(EmployeeNumber), "employeeNumber" },
        { nameof(ErrorType), "errorType" },
        { nameof(IncomeRelationshipNumber), "incomeRelationshipNumber" },
        { nameof(LineNumber), "lineNumber" },
        { nameof(LinePosition), "linePosition" },
        { nameof(ResponseStatus), "responseStatus" },
        { nameof(ResponseType), "responseType" }
    };
}
