// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class PawwDeclarationPatch
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Action), "action" }
    };
}
