// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class PawwDeclaration_period
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(PeriodEndDate), "periodEndDate" },
        { nameof(PeriodId), "periodId" },
        { nameof(PeriodNumber), "periodNumber" },
        { nameof(PeriodStartDate), "periodStartDate" },
        { nameof(PeriodType), "periodType" },
        { nameof(Year), "year" }
    };
}
