// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class Paww
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(AdministrationNumber), "administrationNumber" },
        { nameof(ClientNumber), "clientNumber" },
        { nameof(Contribution), "contribution" },
        { nameof(EmployerName), "employerName" },
        { nameof(GroupCode), "groupCode" },
        { nameof(NumberOfParticipants), "numberOfParticipants" },
        { nameof(PayrollTaxesNumber), "payrollTaxesNumber" },
        { nameof(Period), "period" },
        { nameof(PremiumWage), "premiumWage" },
        { nameof(Year), "year" }
    };
}
