// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class PayGradeAmounts_payGrade_payGradeAmount
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(StartDate), "startDate" },
        { nameof(Value), "value" }
    };
}
