// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class PayGradeAmounts
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(EmploymentId), "employmentId" },
        { nameof(PayGrade), "payGrade" },
        { nameof(PayScale), "payScale" }
    };
}
