// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class Paymentinformationsepaseparatepayments
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Amount), "amount" },
        { nameof(CityBeneficiary), "cityBeneficiary" },
        { nameof(Description1), "description1" },
        { nameof(Description2), "description2" },
        { nameof(EndDate), "endDate" },
        { nameof(Iban), "iban" },
        { nameof(Id), "id" },
        { nameof(NameBeneficiary), "nameBeneficiary" },
        { nameof(StartDate), "startDate" }
    };
}
