// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class Paymentinformationsepa20180101
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Bic), "bic" },
        { nameof(CityBeneficiary), "cityBeneficiary" },
        { nameof(Description1), "description1" },
        { nameof(Description2), "description2" },
        { nameof(Iban), "iban" },
        { nameof(Id), "id" },
        { nameof(NameBeneficiary), "nameBeneficiary" },
        { nameof(PayrollComponent), "payrollComponent" },
        { nameof(VisibleOnPayslip), "visibleOnPayslip" }
    };
}
