// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class PaymentInformationNonSepa
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Bank), "bank" },
        { nameof(BankAccountNumber), "bankAccountNumber" },
        { nameof(Beneficiary), "beneficiary" },
        { nameof(Id), "id" },
        { nameof(PayrollComponent), "payrollComponent" }
    };
}
