// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class PaymentInformationNonSepa_bank
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Address), "address" },
        { nameof(BankIdentifierCode), "bankIdentifierCode" },
        { nameof(City), "city" },
        { nameof(Country), "country" },
        { nameof(Name), "name" }
    };
}
