// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class PayrollRun
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(ApprovalTime), "approvalTime" },
        { nameof(ApprovedBy), "approvedBy" },
        { nameof(AvailableForEmployeeDate), "availableForEmployeeDate" },
        { nameof(ErrorsAndWarnings), "errorsAndWarnings" },
        { nameof(Id), "id" },
        { nameof(MethodOfCreation), "methodOfCreation" },
        { nameof(PayrollPeriod), "payrollPeriod" },
        { nameof(PayrollRunStatus), "payrollRunStatus" },
        { nameof(PayrollTaxReturnPeriod), "payrollTaxReturnPeriod" },
        { nameof(ProcessingFinishedTime), "processingFinishedTime" },
        { nameof(RemoveTime), "removeTime" },
        { nameof(RemovedBy), "removedBy" },
        { nameof(RequestTime), "requestTime" },
        { nameof(RequestedBy), "requestedBy" },
        { nameof(SendEmailToEmployee), "sendEmailToEmployee" },
        { nameof(SequenceNumber), "sequenceNumber" },
        { nameof(SequenceNumberApproved), "sequenceNumberApproved" },
        { nameof(TextPaySlip), "textPaySlip" },
        { nameof(TextPayment), "textPayment" },
        { nameof(TextTariffPaySlip), "textTariffPaySlip" }
    };
}
