// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class PayrollAdministrationConfiguration_defaults_componentSet
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(PayrollPeriodDataCollectiveCategory), "payrollPeriodDataCollectiveCategory" },
        { nameof(PayrollPeriodDataCollectiveComponentSet), "payrollPeriodDataCollectiveComponentSet" },
        { nameof(PayrollPeriodDataEmployeeSelfService), "payrollPeriodDataEmployeeSelfService" },
        { nameof(PayrollPeriodDataIndividual), "payrollPeriodDataIndividual" },
        { nameof(PayrollPeriodDataLeave), "payrollPeriodDataLeave" },
        { nameof(PayrollPeriodDataWerkkosten), "payrollPeriodDataWerkkosten" }
    };
}
