// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class PayrollAdministration
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(AdministrationNumber), "administrationNumber" },
        { nameof(Cla), "cla" },
        { nameof(ClientNumber), "clientNumber" },
        { nameof(GroupClassification), "groupClassification" },
        { nameof(GroupCode), "groupCode" },
        { nameof(Id), "id" },
        { nameof(Name), "name" },
        { nameof(PayrollPeriodType), "payrollPeriodType" },
        { nameof(ShortName), "shortName" },
        { nameof(Wagemodel), "wagemodel" }
    };
}
