// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class PayrollAdministrationWithClaAndWageModel20191216_wageModel
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Value), "value" }
    };
}
