// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class PayrollDataPatch20180101_shift
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(BonusPercentage), "bonusPercentage" },
        { nameof(FullTimeHoursPerWeek), "fullTimeHoursPerWeek" },
        { nameof(ShiftNumber), "shiftNumber" }
    };
}
