// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class PayrollStatus_payroll_userRights
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(HasCalculateWorkingHoursRight), "hasCalculateWorkingHoursRight" },
        { nameof(HasCancelRight), "hasCancelRight" },
        { nameof(HasConfirmRight), "hasConfirmRight" },
        { nameof(HasStartRight), "hasStartRight" }
    };
}
