// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class PayrollDataPatchCollective_payrollComponents
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(IsSupplement), "isSupplement" },
        { nameof(PayrollComponent), "payrollComponent" },
        { nameof(Value), "value" }
    };
}
