// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class PayrollTaxReturn_responseMessages
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(DateOfReceipt), "dateOfReceipt" },
        { nameof(ResponseClass), "responseClass" },
        { nameof(ResponseType), "responseType" }
    };
}
