// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class PayrollPeriodCompare_payrollPeriod
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(PeriodEndDate), "periodEndDate" },
        { nameof(PeriodNumber), "periodNumber" },
        { nameof(PeriodStartDate), "periodStartDate" },
        { nameof(TestYear), "testYear" },
        { nameof(Year), "year" }
    };
}
