// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class PayrollAdministrationWithClaAndWageModel20191216
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Cla), "cla" },
        { nameof(ClientNumber), "clientNumber" },
        { nameof(Description), "description" },
        { nameof(Id), "id" },
        { nameof(Name), "name" },
        { nameof(WageModel), "wageModel" }
    };
}
