// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class PayrollDataPost20180101
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(CostCenter), "costCenter" },
        { nameof(CostUnit), "costUnit" },
        { nameof(DistributionUnit), "distributionUnit" },
        { nameof(Id), "id" },
        { nameof(PayrollComponents), "payrollComponents" },
        { nameof(PayrollPeriod), "payrollPeriod" },
        { nameof(PayslipText), "payslipText" },
        { nameof(PayslipType), "payslipType" },
        { nameof(Shift), "shift" }
    };
}
