// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class PayrollComponentResults_payrollComponentResults
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(PayrollPeriod), "payrollPeriod" },
        { nameof(Value), "value" },
        { nameof(ValueSpecialTariff), "valueSpecialTariff" }
    };
}
