// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class PayrollTaxReturn
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(ApprovalTime), "approvalTime" },
        { nameof(ApprovedBy), "approvedBy" },
        { nameof(CanBeResend), "canBeResend" },
        { nameof(CancelledBy), "cancelledBy" },
        { nameof(CancelledTime), "cancelledTime" },
        { nameof(CorrectionAmount), "correctionAmount" },
        { nameof(DeadlineForPayment), "deadlineForPayment" },
        { nameof(EmailAddressPayrollTaxReturnRunStarted), "emailAddressPayrollTaxReturnRunStarted" },
        { nameof(ExternalIdentification), "externalIdentification" },
        { nameof(Iban), "iban" },
        { nameof(Id), "id" },
        { nameof(InTheNameOf), "inTheNameOf" },
        { nameof(InitiateIdealPayment), "initiateIdealPayment" },
        { nameof(IsCorrectionMessagePriorYear), "isCorrectionMessagePriorYear" },
        { nameof(MessageCreationTime), "messageCreationTime" },
        { nameof(MessageReference), "messageReference" },
        { nameof(MethodOfCreation), "methodOfCreation" },
        { nameof(PaymentReference), "paymentReference" },
        { nameof(PayrollPeriodType), "payrollPeriodType" },
        { nameof(PayrollTaxReturnParty), "payrollTaxReturnParty" },
        { nameof(PayrollTaxReturnStatus), "payrollTaxReturnStatus" },
        { nameof(PayrollTaxReturnType), "payrollTaxReturnType" },
        { nameof(Period), "period" },
        { nameof(PeriodAmount), "periodAmount" },
        { nameof(ProcessingFinishedTime), "processingFinishedTime" },
        { nameof(RemovalTime), "removalTime" },
        { nameof(RemovedBy), "removedBy" },
        { nameof(RequestTime), "requestTime" },
        { nameof(RequestedBy), "requestedBy" },
        { nameof(ResponseMessages), "responseMessages" },
        { nameof(SendTime), "sendTime" },
        { nameof(SequenceNumber), "sequenceNumber" },
        { nameof(TaxReturnMessageReference), "taxReturnMessageReference" },
        { nameof(TotalAmount), "totalAmount" },
        { nameof(WageTaxNumber), "wageTaxNumber" },
        { nameof(WithholdingParty), "withholdingParty" }
    };
}
