// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class PayrollAdministrationVeldenTBVHergebruik
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(AdministrationNumber), "administrationNumber" },
        { nameof(Cao), "cao" },
        { nameof(ClientNumber), "clientNumber" },
        { nameof(Description), "description" },
        { nameof(EmployerId), "employerId" },
        { nameof(EmployerLogo), "employerLogo" },
        { nameof(GroupClassification), "groupClassification" },
        { nameof(GroupCode), "groupCode" },
        { nameof(HasAutomaticPayroll), "hasAutomaticPayroll" },
        { nameof(HasPayrollRunStatusOpen), "HasPayrollRunStatusOpen" },
        { nameof(Id), "id" },
        { nameof(Loonmodel), "loonmodel" },
        { nameof(Name), "name" },
        { nameof(PayrollPeriodType), "payrollPeriodType" }
    };
}
