// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class PayrollRunInitiationvalues
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(AvailableForEmployeeDate), "availableForEmployeeDate" },
        { nameof(EmailAddressPayrollRunApproved), "emailAddressPayrollRunApproved" },
        { nameof(EmailAddressPayrollRunFinished), "emailAddressPayrollRunFinished" },
        { nameof(EmailAddressPayrollRunStarted), "emailAddressPayrollRunStarted" },
        { nameof(PayrollPeriod), "payrollPeriod" },
        { nameof(SendEmailToEmployee), "sendEmailToEmployee" }
    };
}
