// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class PayrollResultsCompact
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(ClientNumber), "clientNumber" },
        { nameof(Department), "department" },
        { nameof(EmployeeNumber), "employeeNumber" },
        { nameof(EmployerCosts), "employerCosts" },
        { nameof(FormattedName), "formattedName" },
        { nameof(Fte), "fte" },
        { nameof(Function), "function" },
        { nameof(Gross), "gross" },
        { nameof(IncomeRelationshipNumber), "incomeRelationshipNumber" },
        { nameof(Net), "net" },
        { nameof(Year), "year" }
    };
}
