// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class PayrollDataPost20180101_payrollComponents_payrollComponent
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(CanBeSupplemented), "canBeSupplemented" },
        { nameof(Category), "category" },
        { nameof(DeductionOrPayment), "deductionOrPayment" },
        { nameof(Key), "key" },
        { nameof(Value), "value" }
    };
}
