// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class PayrollTaxReturnCollective
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(PayrollAdministrationId), "payrollAdministrationId" }
    };
}
