// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class PayrollDataGetPut20180101_costCenter
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Code), "code" },
        { nameof(Description), "description" },
        { nameof(Key), "key" }
    };
}
