// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class PayrollComponentResults
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(EmploymentId), "employmentId" },
        { nameof(PayrollComponentResultsProp), "payrollComponentResults" }
    };
}
