// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class PayrollStatus_payroll
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(AutomaticApproveDate), "automaticApproveDate" },
        { nameof(AutomaticStartDate), "automaticStartDate" },
        { nameof(MethodOfCreation), "methodOfCreation" },
        { nameof(PossibleActions), "possibleActions" },
        { nameof(Status), "status" },
        { nameof(UserRights), "userRights" }
    };
}
