// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class PayrollTaxReturnStatus_payrollTaxReturn_userRights
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(HasConfirmRight), "hasConfirmRight" },
        { nameof(HasStartRight), "hasStartRight" }
    };
}
