// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class PayrollRun_errorsAndWarnings
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(HasErrors), "hasErrors" },
        { nameof(HasWarnings), "hasWarnings" }
    };
}
