// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class PayrollAdministrationGet
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Address), "address" },
        { nameof(AdministrationNumber), "administrationNumber" },
        { nameof(Cao), "cao" },
        { nameof(ClaTaxReturnCBSCode), "claTaxReturnCBSCode" },
        { nameof(ClientNumber), "clientNumber" },
        { nameof(Contact), "contact" },
        { nameof(Description), "description" },
        { nameof(DeviatingPostalAddress), "deviatingPostalAddress" },
        { nameof(EmployerId), "employerId" },
        { nameof(EndDate), "endDate" },
        { nameof(GroupClassification), "groupClassification" },
        { nameof(GroupCode), "groupCode" },
        { nameof(Id), "id" },
        { nameof(Loonmodel), "loonmodel" },
        { nameof(Name), "name" },
        { nameof(PayrollPeriodType), "payrollPeriodType" },
        { nameof(PayrollTaxesNumber), "payrollTaxesNumber" },
        { nameof(ShortName), "shortName" },
        { nameof(StartDate), "startDate" }
    };
}
