// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class PayrollPeriodsMinimized
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(EndDate), "endDate" },
        { nameof(HasApprovedPayrollRun), "hasApprovedPayrollRun" },
        { nameof(HasSuccessfulJournalRun), "hasSuccessfulJournalRun" },
        { nameof(Id), "id" },
        { nameof(PayrollPeriodType), "payrollPeriodType" },
        { nameof(PeriodNumber), "periodNumber" },
        { nameof(StartDate), "startDate" },
        { nameof(TestYear), "testYear" },
        { nameof(Year), "year" }
    };
}
