// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class PayrollAdministrationConfiguration
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(ClientNumber), "clientNumber" },
        { nameof(Defaults), "defaults" },
        { nameof(Description), "description" },
        { nameof(EndDate), "endDate" },
        { nameof(HolidayAllowanceBaseForCalculation), "holidayAllowanceBaseForCalculation" },
        { nameof(HolidayAllowancePercentage), "holidayAllowancePercentage" },
        { nameof(Id), "id" },
        { nameof(PayrollPeriodType), "payrollPeriodType" },
        { nameof(StartDate), "startDate" },
        { nameof(Synchronize), "synchronize" },
        { nameof(YearEndBaseForCalculation), "yearEndBaseForCalculation" },
        { nameof(YearEndPercentage), "yearEndPercentage" }
    };
}
