// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class PayrollAdministrationConfiguration_defaults_componentSet_payrollPeriodDataCollectiveComponentSet
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Description), "description" },
        { nameof(Id), "id" },
        { nameof(RegistrationLevel), "registrationLevel" }
    };
}
