// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class PayrollPeriodCompare
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(NumberOfPayrolledEmployments), "numberOfPayrolledEmployments" },
        { nameof(PayrollComponentResults), "payrollComponentResults" },
        { nameof(PayrollPeriod), "payrollPeriod" }
    };
}
