// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class PayrollComponents
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(CanBeSupplemented), "canBeSupplemented" },
        { nameof(Category), "category" },
        { nameof(DeductionOrPayment), "deductionOrPayment" },
        { nameof(Description), "description" },
        { nameof(IsCollectiveMutationPossible), "isCollectiveMutationPossible" },
        { nameof(Key), "key" }
    };
}
