// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class Payslip400Error_content
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {

    };
}
