// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class PayslipConfigurationObject
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(AddressLocation), "addressLocation" },
        { nameof(DisplayDepartment), "displayDepartment" },
        { nameof(DisplaySalaryScale), "displaySalaryScale" },
        { nameof(DisplaySalutation), "displaySalutation" },
        { nameof(EmployeeNameDisplayMethod), "employeeNameDisplayMethod" },
        { nameof(EmployeeNumberDisplayMethod), "employeeNumberDisplayMethod" },
        { nameof(EmploymentStartDateDisplayMethod), "employmentStartDateDisplayMethod" },
        { nameof(FunctionDisplayMethod), "functionDisplayMethod" },
        { nameof(HourlyWageDisplayMethod), "hourlyWageDisplayMethod" },
        { nameof(Template), "template" }
    };
}
