// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class PensionDeclarationStatus_pensionDeclaration
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(CustomerGroupNumber), "customerGroupNumber" },
        { nameof(ExternalParty), "externalParty" },
        { nameof(MethodOfCreation), "methodOfCreation" },
        { nameof(PensionAdministratorType), "pensionAdministratorType" },
        { nameof(PossibleActions), "possibleActions" },
        { nameof(Status), "status" },
        { nameof(UserRights), "userRights" }
    };
}
