// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class PensionDeclarationCollective
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(ExternalPartyKey), "externalPartyKey" },
        { nameof(PayrollAdministrationId), "payrollAdministrationId" }
    };
}
