// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class PensionBenefits
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(EndDate), "endDate" },
        { nameof(Id), "id" },
        { nameof(Payout), "payout" },
        { nameof(StartDate), "startDate" }
    };
}
