// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class PerformCalculation
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(PayrollPeriod), "payrollPeriod" },
        { nameof(SetAnnualBaseForCalculationsBasedOnFunds), "setAnnualBaseForCalculationsBasedOnFunds" },
        { nameof(SetBaseForCalculations), "setBaseForCalculations" },
        { nameof(SetHoursWorked), "setHoursWorked" },
        { nameof(SetLeaveHours), "setLeaveHours" }
    };
}
