// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class PggmDownloadInformation_payrollRun
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(ApprovalTime), "approvalTime" },
        { nameof(PayrollPeriod), "payrollPeriod" },
        { nameof(PayrollRunId), "payrollRunId" },
        { nameof(ProcessingFinishedTime), "processingFinishedTime" },
        { nameof(RequestTime), "requestTime" },
        { nameof(SequenceNumberApproved), "sequenceNumberApproved" },
        { nameof(TextPaySlip), "textPaySlip" },
        { nameof(TextPayment), "textPayment" }
    };
}
