// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class PggmInitiationInformation
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(PayrollPeriod), "payrollPeriod" },
        { nameof(ReferenceDate), "referenceDate" }
    };
}
