// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class PggmDownloadInput_dataProvider
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(DeviatingConnectionNumber), "deviatingConnectionNumber" },
        { nameof(DeviatingName), "deviatingName" }
    };
}
