// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class PostPayrollRun_initiationParameters
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(EmailAddressPayrollRunFinished), "emailAddressPayrollRunFinished" },
        { nameof(EmailAddressPayrollRunStarted), "emailAddressPayrollRunStarted" },
        { nameof(TypeOfInitiation), "typeOfInitiation" }
    };
}
