// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class PostPreboardingTrajectory
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Fragments), "fragments" }
    };
}
