// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class PostPayrollRunCollective
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(AvailableForEmployeeDate), "availableForEmployeeDate" },
        { nameof(InitialisePayrollPeriod), "initialisePayrollPeriod" },
        { nameof(PayrollAdministrationId), "payrollAdministrationId" }
    };
}
