// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class ProformaStatus
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(ActiveFor), "activeFor" },
        { nameof(Status), "status" }
    };
}
