// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class PropertiesEmployments_payrollPeriods_payslipTypes
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(PayrollComponentResults), "payrollComponentResults" },
        { nameof(PayslipType), "payslipType" }
    };
}
