// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class ProposedLeaveHoursResponse
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(AdditionalInformation), "additionalInformation" },
        { nameof(EmploymentId), "employmentId" },
        { nameof(MethodOfCalculation), "methodOfCalculation" },
        { nameof(ProposedLeaveHours), "proposedLeaveHours" }
    };
}
