// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class Protectedearnings
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(EndDate), "endDate" },
        { nameof(Id), "id" },
        { nameof(StartDate), "startDate" },
        { nameof(Threshold), "threshold" }
    };
}
