// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class ProviderSettings
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(AdministrationNumber), "administrationNumber" },
        { nameof(GroupCode), "groupCode" },
        { nameof(ParentEmployerForConsolidatedOverviews), "parentEmployerForConsolidatedOverviews" },
        { nameof(SendEmailWhenSalarySlipIsAvailable), "sendEmailWhenSalarySlipIsAvailable" }
    };
}
