// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class ProviderContactInformation
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Address), "address" },
        { nameof(Contact), "contact" },
        { nameof(Id), "id" },
        { nameof(Name), "name" }
    };
}
