// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class ProviderContactInformation_contact
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Email), "email" },
        { nameof(Faxnumber), "faxnumber" },
        { nameof(Name), "name" },
        { nameof(Phonenumber), "phonenumber" }
    };
}
