// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class Provider
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Id), "id" },
        { nameof(Name), "name" }
    };
}
