// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class QwoaterObject
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Id), "id" },
        { nameof(LastModifiedVersionNumber), "lastModifiedVersionNumber" },
        { nameof(ProviderId), "providerId" }
    };
}
