// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class ReceiptOcrResults_payrollComponent
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(ComponentId), "componentId" },
        { nameof(DeviatingDescription), "deviatingDescription" },
        { nameof(Name), "name" }
    };
}
