// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class ReceiptOcrResults
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(BoundingRegion), "boundingRegion" },
        { nameof(Confidence), "confidence" },
        { nameof(MerchantName), "merchantName" },
        { nameof(PayrollComponent), "payrollComponent" },
        { nameof(SubTotal), "subTotal" },
        { nameof(Total), "total" },
        { nameof(TotalTax), "totalTax" },
        { nameof(TransactionDate), "transactionDate" },
        { nameof(TransactionTime), "transactionTime" }
    };
}
