// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class ReceiptOcrResults_total
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(BoundingRegion), "boundingRegion" },
        { nameof(Confidence), "confidence" },
        { nameof(Value), "value" }
    };
}
