// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class Reintegration
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(DateOfFinalizingPlanOfAction), "dateOfFinalizingPlanOfAction" },
        { nameof(ReintegrationGoal), "reintegrationGoal" }
    };
}
