// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class ResponsesMessageWarning
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Messages), "messages" }
    };
}
