// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class RouteObject
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(LengthInKilometers), "lengthInKilometers" },
        { nameof(RouteType), "routeType" }
    };
}
