// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class SchemasPayrollResults_payrollPeriods_payslipTypes_payrollComponentResults_payrollComponent
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Category), "category" },
        { nameof(Column), "column" },
        { nameof(CostsEmployer), "costsEmployer" },
        { nameof(Key), "key" },
        { nameof(Value), "value" }
    };
}
