// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class SchemasLeaveType_leaveType
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(BalanceExceedsYear), "balanceExceedsYear" },
        { nameof(EmployeeCanRequestIncrease), "employeeCanRequestIncrease" },
        { nameof(Enabled), "enabled" },
        { nameof(Key), "key" },
        { nameof(Value), "value" }
    };
}
