// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class SchemasFiscal
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(AnnualSalary), "annualSalary" },
        { nameof(ApplyDayTables), "applyDayTables" },
        { nameof(ApplyDeviatingPayrollTaxPercentageOn), "applyDeviatingPayrollTaxPercentageOn" },
        { nameof(ApplyPayrollTaxDeduction), "applyPayrollTaxDeduction" },
        { nameof(ApplySalarysplit), "applySalarysplit" },
        { nameof(ApplySingleElderlyTaxDeduction), "applySingleElderlyTaxDeduction" },
        { nameof(ApplyStudentDeduction), "applyStudentDeduction" },
        { nameof(ContributionReductionEducation), "contributionReductionEducation" },
        { nameof(DeviatingCalculationRulePayrollTax), "deviatingCalculationRulePayrollTax" },
        { nameof(DeviatingPayrollTaxPercentage), "deviatingPayrollTaxPercentage" },
        { nameof(DeviatingPayrollTaxTableColour), "deviatingPayrollTaxTableColour" },
        { nameof(DeviatingPercentageThirtyPercentFacility), "deviatingPercentageThirtyPercentFacility" },
        { nameof(DeviatingSmallJobsArrangement), "deviatingSmallJobsArrangement" },
        { nameof(DeviatingTaxTableCode), "deviatingTaxTableCode" },
        { nameof(DoesWageIncludeAow), "doesWageIncludeAow" },
        { nameof(DoesWageIncludeWajong), "doesWageIncludeWajong" },
        { nameof(EndDate), "endDate" },
        { nameof(HasEmployeeLoan), "hasEmployeeLoan" },
        { nameof(Id), "id" },
        { nameof(PercentageForeignIncome), "percentageForeignIncome" },
        { nameof(ResidentOf), "residentOf" },
        { nameof(SpecialIndication), "specialIndication" },
        { nameof(StartDate), "startDate" },
        { nameof(ThirtyPercentFacility), "thirtyPercentFacility" },
        { nameof(UsesTransportByWithholdingAgent), "usesTransportByWithholdingAgent" }
    };
}
