// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class SchemasOtherPayrollVariables_pensionProperties_leaveAbp
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(LeaveType), "leaveType" },
        { nameof(ValueOfParticipationDuringLeave), "valueOfParticipationDuringLeave" }
    };
}
