// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class SchemasWorkingHours_workPattern
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(EvenWeeks), "evenWeeks" },
        { nameof(OddWeeks), "oddWeeks" }
    };
}
