// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class SchemasSocialSecurity
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(EndDate), "endDate" },
        { nameof(Id), "id" },
        { nameof(IsInsuredForOccupationalDisabilityInsuranceAct), "isInsuredForOccupationalDisabilityInsuranceAct" },
        { nameof(IsInsuredForSicknessBenefitsAct), "isInsuredForSicknessBenefitsAct" },
        { nameof(IsInsuredForUnemploymentInsuranceAct), "isInsuredForUnemploymentInsuranceAct" },
        { nameof(StartDate), "startDate" }
    };
}
