// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class SchemasUserResponsibility
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Id), "id" },
        { nameof(Name), "name" },
        { nameof(NumberOfLinkedUsers), "numberOfLinkedUsers" },
        { nameof(Origin), "origin" }
    };
}
