// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class SchemasLinkedEmployment
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Employee), "employee" },
        { nameof(EndDate), "endDate" },
        { nameof(Id), "id" },
        { nameof(IncomeRelationshipNumber), "incomeRelationshipNumber" },
        { nameof(StartDate), "startDate" }
    };
}
