// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class SchemasEmailTemplate_type
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Description), "description" },
        { nameof(Id), "id" },
        { nameof(SortOrder), "sortOrder" }
    };
}
