// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class SchemasWage
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(ApplyPayGrade), "applyPayGrade" },
        { nameof(EmployerCosts), "employerCosts" },
        { nameof(EmployerCostsType), "employerCostsType" },
        { nameof(EndDate), "endDate" },
        { nameof(GrossWage), "grossWage" },
        { nameof(GrossWageType), "grossWageType" },
        { nameof(Id), "id" },
        { nameof(IsGrossWageFullTime), "isGrossWageFullTime" },
        { nameof(NetWage), "netWage" },
        { nameof(NetWageType), "netWageType" },
        { nameof(PayGrade), "payGrade" },
        { nameof(PayScale), "payScale" },
        { nameof(PayrollPeriodType), "payrollPeriodType" },
        { nameof(StartDate), "startDate" }
    };
}
