// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class SchemasLeave
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Comments), "comments" },
        { nameof(EmploymentId), "employmentId" },
        { nameof(EndDate), "endDate" },
        { nameof(IsAccrual), "isAccrual" },
        { nameof(LeaveType), "leaveType" },
        { nameof(NumberOfUnits), "numberOfUnits" },
        { nameof(StartDate), "startDate" }
    };
}
