// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class SchemasNotesByEmployer_concerningEmployee
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(EmployeeNumber), "employeeNumber" },
        { nameof(FormattedName), "formattedName" }
    };
}
