// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class SchemasChangeAddressRequest
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Address), "address" },
        { nameof(Comment), "comment" },
        { nameof(EffectiveFromDate), "effectiveFromDate" }
    };
}
