// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class SchemasUserPost_ssoAccount
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Password), "password" },
        { nameof(UserName), "userName" }
    };
}
