// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class SchemasPayrollResults
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(EmploymentId), "employmentId" },
        { nameof(PayrollPeriods), "payrollPeriods" }
    };
}
