// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class SchemasPayrollResults_payrollPeriods
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(PayrollPeriod), "payrollPeriod" },
        { nameof(PayslipTypes), "payslipTypes" }
    };
}
