// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class SchemasDashboard
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(EmbedToken), "embedToken" },
        { nameof(EmbedUrl), "embedUrl" },
        { nameof(Id), "id" },
        { nameof(Name), "name" }
    };
}
