// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class SchemasConfigurationObject
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(DefaultProviderLogo), "defaultProviderLogo" },
        { nameof(EnableAutomaticDataDeletion), "enableAutomaticDataDeletion" },
        { nameof(IsEditNotitionAllowed), "isEditNotitionAllowed" },
        { nameof(PayrollTaxReturnParty), "payrollTaxReturnParty" }
    };
}
