// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class SchemasPayslip
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(ApprovalTime), "approvalTime" },
        { nameof(NumberOfPayslips), "numberOfPayslips" },
        { nameof(PayrollPeriod), "payrollPeriod" },
        { nameof(PayrollrunId), "payrollrunId" }
    };
}
