// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class SchemasLeaveType
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Deviations), "deviations" },
        { nameof(Id), "id" },
        { nameof(LeaveType), "leaveType" }
    };
}
