// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class SchemasAuthorizationGroupObject_currentUser
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(IsAuthorizedToAddPayrollAdministrations), "isAuthorizedToAddPayrollAdministrations" },
        { nameof(IsAuthorizedToManageEmployerAuthorizationGroups), "isAuthorizedToManageEmployerAuthorizationGroups" },
        { nameof(IsAuthorizedToManageEmployerModules), "isAuthorizedToManageEmployerModules" }
    };
}
