// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class SchemasAzureActiveDirectory
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Tenant), "tenant" },
        { nameof(UserId), "userId" }
    };
}
