// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class SchemasPayrollData
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(CostCenter), "costCenter" },
        { nameof(CostUnit), "costUnit" },
        { nameof(DistributionUnit), "distributionUnit" },
        { nameof(Employee), "employee" },
        { nameof(Employment), "employment" },
        { nameof(PayrollComponents), "payrollComponents" },
        { nameof(PayrollPeriod), "payrollPeriod" },
        { nameof(PayslipType), "payslipType" },
        { nameof(Shift), "shift" }
    };
}
