// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class SchemasEmailTemplate
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Category), "category" },
        { nameof(DefinedAtLevel), "definedAtLevel" },
        { nameof(DependsOnModule), "dependsOnModule" },
        { nameof(Email), "email" },
        { nameof(IsEmailTemplateEditable), "isEmailTemplateEditable" },
        { nameof(Type), "type" }
    };
}
