// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class SchemasFundTotal
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Deviations), "deviations" },
        { nameof(EndDate), "endDate" },
        { nameof(FixedContribution), "fixedContribution" },
        { nameof(Fund), "fund" },
        { nameof(Id), "id" },
        { nameof(StartDate), "startDate" }
    };
}
