// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class SchemasOtherPayrollVariables
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(EndDate), "endDate" },
        { nameof(Id), "id" },
        { nameof(InsuranceProperties), "insuranceProperties" },
        { nameof(PayrollProperties), "payrollProperties" },
        { nameof(PensionProperties), "pensionProperties" },
        { nameof(ProductivityPercentage), "productivityPercentage" },
        { nameof(StartDate), "startDate" }
    };
}
