// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class SchemasCollectiveAction
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(CollectiveActionId), "collectiveActionId" },
        { nameof(CollectiveActionParentId), "collectiveActionParentId" },
        { nameof(EmployerId), "employerId" },
        { nameof(ItemCount), "itemCount" },
        { nameof(PayrollAdministrationId), "payrollAdministrationId" },
        { nameof(Status), "status" },
        { nameof(SubmittedByUserId), "submittedByUserId" },
        { nameof(SubmittedOn), "submittedOn" },
        { nameof(Type), "type" }
    };
}
