// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class SchemasNotification
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(NotificationSet), "notificationSet" },
        { nameof(Notifications), "notifications" }
    };
}
