// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class SchemasOrganizationalEntity
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Department), "department" },
        { nameof(DeviatingFunctionDescription), "deviatingFunctionDescription" },
        { nameof(DeviatingFunctionGroup), "deviatingFunctionGroup" },
        { nameof(DistributionUnit), "distributionUnit" },
        { nameof(EndDate), "endDate" },
        { nameof(Function), "function" },
        { nameof(Id), "id" },
        { nameof(InternalTelephoneExtensionNumber), "internalTelephoneExtensionNumber" },
        { nameof(PlaceOfEmployment), "placeOfEmployment" },
        { nameof(StandardFunction), "standardFunction" },
        { nameof(StartDate), "startDate" }
    };
}
