// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class SchemasPayrollData_employee
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(EmployeeNumber), "employeeNumber" },
        { nameof(FirstName), "firstName" },
        { nameof(FormattedName), "formattedName" }
    };
}
