// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class SchemasOtherPayrollVariables_insuranceProperties
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(ApplicableForNoRiskPolicy), "applicableForNoRiskPolicy" }
    };
}
