// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class SchemasLinkedUsers
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(CreatedOn), "createdOn" },
        { nameof(Isblocked), "isblocked" },
        { nameof(LastLogin), "lastLogin" },
        { nameof(User), "user" }
    };
}
