// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class SchemasCitizenServiceNumber
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(CitizenServiceNumber), "citizenServiceNumber" }
    };
}
