// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class SchemasPatchUserInvite
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Action), "action" },
        { nameof(ResendInformation), "resendInformation" }
    };
}
