// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class SchemasOtherPayrollVariables_payrollProperties_collectiveLaborAgreementCodeHiringEmployer
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(EndDate), "endDate" },
        { nameof(Key), "key" },
        { nameof(StartDate), "startDate" },
        { nameof(Value), "value" }
    };
}
