// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class SchemasPayrollData_payrollComponents_payrollComponent
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(CanBeSupplemented), "canBeSupplemented" },
        { nameof(Category), "category" },
        { nameof(DeductionOrPayment), "deductionOrPayment" },
        { nameof(Description), "description" },
        { nameof(DeviatingDescription), "deviatingDescription" },
        { nameof(Key), "key" }
    };
}
