// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class SchemasPayrollData_employment
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Id), "id" },
        { nameof(IncomeRelationshipNumber), "incomeRelationshipNumber" },
        { nameof(PayrollId), "payrollId" }
    };
}
