// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class SchemasChangeContactInformationRequest
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Comment), "comment" },
        { nameof(EmailAddress), "emailAddress" },
        { nameof(MobilePhoneNumber), "mobilePhoneNumber" },
        { nameof(PhoneNumber), "phoneNumber" }
    };
}
