// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class SchemasOtherPayrollVariables_pensionProperties
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(AnnualCalculationBaseAbp), "annualCalculationBaseAbp" },
        { nameof(ApplyDispensationRiskFund), "applyDispensationRiskFund" },
        { nameof(CompulsoryEducationDays), "compulsoryEducationDays" },
        { nameof(DeviatingDisabilityInsuranceActPercentageForCordares), "deviatingDisabilityInsuranceActPercentageForCordares" },
        { nameof(LeaveAbp), "leaveAbp" },
        { nameof(OccupationalPensionFund), "occupationalPensionFund" },
        { nameof(SpecificationOfIncomeRelationshipApg), "specificationOfIncomeRelationshipApg" }
    };
}
