// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class SchemasDashboard_embedToken
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Expiration), "expiration" },
        { nameof(Token), "token" }
    };
}
