// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class SchemasEmailTemplate_email
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Body), "body" },
        { nameof(SenderEmail), "senderEmail" },
        { nameof(Subject), "subject" }
    };
}
