// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class SchemasAzureActiveDirectory_tenant
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Description), "description" },
        { nameof(Id), "id" },
        { nameof(TenantRegistrationLevel), "tenantRegistrationLevel" }
    };
}
