// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class SchemasCreate
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Action), "action" },
        { nameof(Address), "address" },
        { nameof(Comment), "comment" },
        { nameof(Description), "description" },
        { nameof(Name), "name" },
        { nameof(Particularities), "particularities" },
        { nameof(PhoneNumber), "phoneNumber" }
    };
}
