// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class SchemasOtherPayrollVariables_payrollProperties
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(ApplyMinimumWageVocationalLearningPathway), "applyMinimumWageVocationalLearningPathway" },
        { nameof(ApplyYearlyHoursNorm), "applyYearlyHoursNorm" },
        { nameof(CollectiveLaborAgreementCodeHiringEmployer), "collectiveLaborAgreementCodeHiringEmployer" },
        { nameof(DeviatingPremiumGroup), "deviatingPremiumGroup" },
        { nameof(IncidentalIncomeDeduction), "incidentalIncomeDeduction" },
        { nameof(OccupationalDisabilityDeductionAfter2009), "occupationalDisabilityDeductionAfter2009" },
        { nameof(OccupationalDisabilityDeductionTo2009), "occupationalDisabilityDeductionTo2009" },
        { nameof(OccupationalDisabilityPremiumDiscount), "occupationalDisabilityPremiumDiscount" },
        { nameof(PhaseClassification), "phaseClassification" },
        { nameof(TerminateIncomenumberFlexibleEmployment), "terminateIncomenumberFlexibleEmployment" },
        { nameof(WageCostBenefit), "wageCostBenefit" },
        { nameof(WajongWithWageDispensation), "wajongWithWageDispensation" }
    };
}
