// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class SchemasInitiationParametersForPreviousPayrollYear
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(PayrollYear), "payrollYear" }
    };
}
