// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class SepaHashes
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Hash), "hash" },
        { nameof(SepaFileDescription), "sepaFileDescription" }
    };
}
