// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class SignatureDocumentStatusObject
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(SignDocumentStatus), "signDocumentStatus" }
    };
}
