// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class SignatureStatusObject
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(SignDocumentStatus), "signDocumentStatus" },
        { nameof(SignerStatus), "signerStatus" }
    };
}
