// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class SignatureDocumentStatusObject_signDocumentStatus
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Key), "Key" },
        { nameof(Value), "Value" }
    };
}
