// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class SignatureStatusObject_signerStatus
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Declined), "declined" },
        { nameof(EmailAddress), "emailAddress" },
        { nameof(Emailed), "emailed" },
        { nameof(Name), "name" },
        { nameof(Signed), "signed" },
        { nameof(SignedOnDate), "signedOnDate" },
        { nameof(Viewed), "viewed" }
    };
}
