// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class SmartPasteData_context
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(EmployerId), "employerId" },
        { nameof(Language), "language" },
        { nameof(OrderBy), "orderBy" },
        { nameof(PageNumber), "pageNumber" },
        { nameof(PageSize), "pageSize" },
        { nameof(PayrollComponentSet), "payrollComponentSet" },
        { nameof(PayslipType), "payslipType" }
    };
}
