// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class SmartPasteResults_remarks
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Message), "message" },
        { nameof(Type), "type" }
    };
}
