// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class SmartPasteData
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Clipboard), "clipboard" },
        { nameof(Context), "context" },
        { nameof(PayrollData), "payrollData" }
    };
}
