// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class SmartPasteResults
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Context), "context" },
        { nameof(Id), "id" },
        { nameof(Remarks), "remarks" },
        { nameof(Results), "results" },
        { nameof(Status), "status" }
    };
}
