// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class SmartPasteData_clipboard_clipboardFiles
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Base64Content), "base64Content" },
        { nameof(MimeType), "mimeType" }
    };
}
