// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class SocialSecurity
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(HealthCareInsuranceActType), "healthCareInsuranceActType" },
        { nameof(IsInsuredForOccupationalDisabilityInsuranceAct), "isInsuredForOccupationalDisabilityInsuranceAct" },
        { nameof(IsInsuredForSicknessBenefitsAct), "isInsuredForSicknessBenefitsAct" },
        { nameof(IsInsuredForUnemploymentInsuranceAct), "isInsuredForUnemploymentInsuranceAct" }
    };
}
