// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class SpecialIndication
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Four), "four" },
        { nameof(One), "one" },
        { nameof(Three), "three" },
        { nameof(Two), "two" }
    };
}
