// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class StandardFunction
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Category), "category" },
        { nameof(Code), "code" },
        { nameof(Key), "key" },
        { nameof(Value), "value" }
    };
}
