// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class StippInitiationInformation
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(EmailAddress), "emailAddress" },
        { nameof(PayrollPeriod), "payrollPeriod" },
        { nameof(ReferenceDate), "referenceDate" }
    };
}
