// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class StippDownloadInformation
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(PayrollRun), "payrollRun" }
    };
}
