// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class StippDownloadInput_dataProvider
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Address), "address" },
        { nameof(Name), "name" }
    };
}
