// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class Synchronize
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(ContactInformation), "contactInformation" },
        { nameof(NameAndAddress), "nameAndAddress" }
    };
}
