// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class TaskObject
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Assignees), "assignees" },
        { nameof(Description), "description" },
        { nameof(SendEmail), "sendEmail" },
        { nameof(TaskId), "taskId" },
        { nameof(TaskType), "taskType" }
    };
}
