// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class Travel
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(TravelDistanceToWork), "travelDistanceToWork" },
        { nameof(TravelDistanceToWorkInKm), "travelDistanceToWorkInKm" }
    };
}
