// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class UpaPensionDeclaration
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(ApprovalTime), "approvalTime" },
        { nameof(ApprovedBy), "approvedBy" },
        { nameof(CancelledBy), "cancelledBy" },
        { nameof(CancelledTime), "cancelledTime" },
        { nameof(CreationTime), "creationTime" },
        { nameof(ExternalParty), "externalParty" },
        { nameof(Id), "id" },
        { nameof(MessageReference), "messageReference" },
        { nameof(MethodOfCreation), "methodOfCreation" },
        { nameof(PayrollTaxesNumber), "payrollTaxesNumber" },
        { nameof(Period), "period" },
        { nameof(RemoveTime), "removeTime" },
        { nameof(RemovedBy), "removedBy" },
        { nameof(RequestTime), "requestTime" },
        { nameof(RequestedBy), "requestedBy" },
        { nameof(ResponseMessages), "responseMessages" },
        { nameof(SendingPartyNumber), "sendingPartyNumber" },
        { nameof(SentTime), "sentTime" },
        { nameof(UpaPensionDeclarationStatus), "upaPensionDeclarationStatus" },
        { nameof(WithholdingAgentName), "withholdingAgentName" }
    };
}
