// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class UserSet_user
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(UserCustomSpecifiedRole), "userCustomSpecifiedRole" },
        { nameof(UserSpecifiedRole), "userSpecifiedRole" }
    };
}
