// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class UserSettings_employmentFilter
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(FilterOnAdministrations), "filterOnAdministrations" },
        { nameof(FilterOnDepartments), "filterOnDepartments" },
        { nameof(FilterOnEmployedStatus), "filterOnEmployedStatus" },
        { nameof(FilterOnEmploymentTypes), "filterOnEmploymentTypes" },
        { nameof(FilterOnFunctions), "filterOnFunctions" },
        { nameof(FilterOnOnCallEmployment), "filterOnOnCallEmployment" },
        { nameof(ReferenceDate), "referenceDate" }
    };
}
