// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class UserBasicNotNullable
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(FormattedName), "formattedName" },
        { nameof(Id), "id" },
        { nameof(Initials), "initials" },
        { nameof(LastName), "lastName" },
        { nameof(Prefix), "prefix" }
    };
}
