// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class UsersObject
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(HasAuthorizationsOnUserLevel), "hasAuthorizationsOnUserLevel" },
        { nameof(HasIntegrations), "hasIntegrations" },
        { nameof(HasMultipleTeams), "hasMultipleTeams" },
        { nameof(Id), "id" },
        { nameof(IsLinked), "isLinked" },
        { nameof(PersonalDetails), "personalDetails" },
        { nameof(UserName), "userName" }
    };
}
