// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class UserPost_azureActiveDirectory
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Tenant), "tenant" },
        { nameof(UserId), "userId" },
        { nameof(UserName), "userName" }
    };
}
