// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class UserSet
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(ContactInformation), "contactInformation" },
        { nameof(PersonalDetails), "personalDetails" },
        { nameof(Photo), "photo" },
        { nameof(User), "user" }
    };
}
