// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class UserSettings
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(EmploymentFilter), "employmentFilter" }
    };
}
