// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class UserInvite
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(ContactInformation), "contactInformation" },
        { nameof(DestinationForSecret), "destinationForSecret" },
        { nameof(HasAccessToPayrollingTestData), "hasAccessToPayrollingTestData" },
        { nameof(PersonalDetails), "personalDetails" },
        { nameof(TwoFactorAuthenticationRequired), "twoFactorAuthenticationRequired" }
    };
}
