// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class UserMinimized
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(PersonalDetails), "personalDetails" }
    };
}
