// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class VersionObject1
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(ObsoleteDate), "obsoleteDate" },
        { nameof(ResourceVersion), "resourceVersion" }
    };
}
