// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class Wachtgeld
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(EndDate), "endDate" },
        { nameof(Id), "id" },
        { nameof(StartDate), "startDate" },
        { nameof(Value), "value" },
        { nameof(ValueAdditionalIncomeCivilService), "valueAdditionalIncomeCivilService" },
        { nameof(ValueAdditionalIncomeNonCivilService), "valueAdditionalIncomeNonCivilService" }
    };
}
