// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class WageImportData
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(ClientNumber), "clientNumber" },
        { nameof(EmployeeNumber), "employeeNumber" },
        { nameof(EmployerCosts), "employerCosts" },
        { nameof(EmployerCostsTypeKey), "employerCostsTypeKey" },
        { nameof(FormattedName), "formattedName" },
        { nameof(GrossWage), "grossWage" },
        { nameof(GrossWageTypeKey), "grossWageTypeKey" },
        { nameof(NetWage), "netWage" },
        { nameof(NetWageTypeKey), "netWageTypeKey" },
        { nameof(PayrollEmployeeNumber), "payrollEmployeeNumber" },
        { nameof(StartDate), "startDate" }
    };
}
