// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class WageProposalObject_employmentInformation
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Department), "department" },
        { nameof(EmployeeNumber), "employeeNumber" },
        { nameof(FirstName), "firstName" },
        { nameof(FormattedName), "formattedName" },
        { nameof(Function), "function" },
        { nameof(Id), "id" },
        { nameof(IncomeRelationshipNumber), "incomeRelationshipNumber" },
        { nameof(PayrollAdministration), "payrollAdministration" },
        { nameof(Photo), "photo" }
    };
}
