// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class WageProposalObject
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(CurrentGrossWage), "currentGrossWage" },
        { nameof(CurrentPayGrade), "currentPayGrade" },
        { nameof(EmploymentInformation), "employmentInformation" },
        { nameof(GrossWageType), "grossWageType" },
        { nameof(Id), "id" },
        { nameof(PayScale), "payScale" },
        { nameof(ProposalReason), "proposalReason" },
        { nameof(ProposedGrossWage), "proposedGrossWage" },
        { nameof(ProposedPayGrade), "proposedPayGrade" },
        { nameof(StartDateProposal), "startDateProposal" },
        { nameof(Status), "status" }
    };
}
