// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class WageProposalObject_employmentInformation_payrollAdministration
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(ClientNumber), "clientNumber" },
        { nameof(Description), "description" },
        { nameof(Id), "id" },
        { nameof(Name), "name" }
    };
}
