// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class WageProjectionInput_deviations
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(HoursPerWeek), "hoursPerWeek" },
        { nameof(PercentageChange), "percentageChange" },
        { nameof(StartDate), "startDate" }
    };
}
