// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class WageCollective
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(EmploymentId), "employmentId" },
        { nameof(GrossWage), "grossWage" },
        { nameof(StartDate), "startDate" }
    };
}
