// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class WagePercentages
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(EndDate), "endDate" },
        { nameof(HolidayAllowancePercentage), "holidayAllowancePercentage" },
        { nameof(Id), "id" },
        { nameof(StartDate), "startDate" },
        { nameof(YearEndPercentage), "yearEndPercentage" }
    };
}
