// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class Wage
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(ApplyPayGrade), "applyPayGrade" },
        { nameof(GrossWage), "grossWage" },
        { nameof(GrossWageType), "grossWageType" },
        { nameof(NetWage), "netWage" },
        { nameof(NetWageType), "netWageType" },
        { nameof(PayGrade), "payGrade" },
        { nameof(PayScale), "payScale" }
    };
}
