// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class WithdrawParameters
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(AddWithdrawalTo), "addWithdrawalTo" },
        { nameof(CitizenServiceNumber), "citizenServiceNumber" },
        { nameof(IncomeRelationshipNumber), "incomeRelationshipNumber" },
        { nameof(PayrollId), "payrollId" }
    };
}
