// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class WithPaymentInformationSepa400Error
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Content), "content" },
        { nameof(Messages), "messages" },
        { nameof(Version), "version" }
    };
}
