// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class WorkingHours
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(AverageParttimeFactor), "averageParttimeFactor" },
        { nameof(CalculateUsingWorkPattern), "calculateUsingWorkPattern" },
        { nameof(ContractCode), "contractCode" },
        { nameof(DeviatingHoursPerWeek), "deviatingHoursPerWeek" },
        { nameof(DeviatingSvDaysPerPeriod), "deviatingSvDaysPerPeriod" },
        { nameof(FlexibleHoursContract), "flexibleHoursContract" },
        { nameof(RegularWorkPattern), "regularWorkPattern" },
        { nameof(Shift), "shift" },
        { nameof(WorkPattern), "workPattern" }
    };
}
