// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class WorkflowTriggerMapping
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(CreatedBy), "createdBy" },
        { nameof(CreatedOn), "createdOn" },
        { nameof(Id), "id" },
        { nameof(LastModifiedBy), "lastModifiedBy" },
        { nameof(LastModifiedOn), "lastModifiedOn" },
        { nameof(Trigger), "trigger" },
        { nameof(WorkflowTemplate), "workflowTemplate" }
    };
}
