// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class Workflowtriggermappings
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Code), "code" },
        { nameof(Description), "description" },
        { nameof(Id), "id" },
        { nameof(Properties), "properties" },
        { nameof(Type), "type" }
    };
}
