// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class Workflows_assignees
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Role), "role" },
        { nameof(User), "user" },
        { nameof(UserResponsibility), "userResponsibility" }
    };
}
