// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class WorkflowIds
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(WorkflowIdsProp), "workflowIds" }
    };
}
