// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class WorkRelatedCostsSchemeFinancialsObject
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Amount), "amount" },
        { nameof(Description), "description" },
        { nameof(Id), "id" },
        { nameof(Identification), "identification" },
        { nameof(Period), "period" },
        { nameof(Year), "year" }
    };
}
