// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class WorkflowTemplate
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Id), "id" },
        { nameof(Tasks), "tasks" },
        { nameof(UserInstruction), "userInstruction" }
    };
}
