// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class Workflows_comments
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Comment), "comment" },
        { nameof(CommentedBy), "commentedBy" },
        { nameof(CommentedOn), "commentedOn" }
    };
}
