// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class Workflows_comment
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Id), "id" },
        { nameof(Text), "text" },
        { nameof(Timestamp), "timestamp" },
        { nameof(UserId), "userId" }
    };
}
