// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class WorkflowTrigger
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Category), "category" },
        { nameof(Description), "description" },
        { nameof(Id), "id" },
        { nameof(WorkflowTemplate), "workflowTemplate" }
    };
}
