// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class Workflows_allowedTransitions
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Description), "description" },
        { nameof(Href), "href" },
        { nameof(HttpVerb), "httpVerb" },
        { nameof(Transitions), "transitions" }
    };
}
