// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class WorkRelatedCostsSchemeMatrixObject
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(DiscretionaryScopeCumulative), "discretionaryScopeCumulative" },
        { nameof(PayrollPeriod), "payrollPeriod" },
        { nameof(WorkRelatedCostsCumulative), "workRelatedCostsCumulative" }
    };
}
