// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class Workflows_allowedTransitions_transitions
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Action), "action" },
        { nameof(Data), "data" },
        { nameof(Description), "description" }
    };
}
