// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class Workflows_currentTask
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Type), "type" }
    };
}
