// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class Workflows
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(AllowedTransitions), "allowedTransitions" },
        { nameof(ApiParams), "apiParams" },
        { nameof(ApiPayload), "apiPayload" },
        { nameof(ApiViewModel), "apiViewModel" },
        { nameof(Assignees), "assignees" },
        { nameof(CanBeCancelledByInitiator), "canBeCancelledByInitiator" },
        { nameof(CanBeEditedByInitiator), "canBeEditedByInitiator" },
        { nameof(Comment), "comment" },
        { nameof(Comments), "comments" },
        { nameof(CurrentTask), "currentTask" },
        { nameof(FunctionalStatus), "functionalStatus" },
        { nameof(Id), "id" },
        { nameof(InitiatedBy), "initiatedBy" },
        { nameof(InitiatedOn), "initiatedOn" },
        { nameof(LastModifiedBy), "lastModifiedBy" },
        { nameof(LastModifiedOn), "lastModifiedOn" },
        { nameof(Status), "status" },
        { nameof(Trigger), "trigger" },
        { nameof(WorkflowTemplate), "workflowTemplate" }
    };
}
