// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class YearEndStatementsReport_payrollYear
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(TestYear), "testYear" },
        { nameof(Year), "year" }
    };
}
