// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class YearStatus_year_userRights
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(HasRequestTranstionRight), "hasRequestTranstionRight" }
    };
}
