// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class YearTransitionPatch
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(DateAvailableEss), "dateAvailableEss" },
        { nameof(SentEssMail), "sentEssMail" }
    };
}
