// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class Yearsofservicebasedleave400Error
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(CurrentPage), "currentPage" },
        { nameof(Embedded), "_embedded" },
        { nameof(Messages), "messages" },
        { nameof(PageSize), "pageSize" },
        { nameof(TotalPages), "totalPages" },
        { nameof(TotalSize), "totalSize" },
        { nameof(Version), "version" }
    };
}
