// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class YearTransitionCollective
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(DateAvailableEss), "dateAvailableEss" },
        { nameof(PayrollAdministrationId), "payrollAdministrationId" },
        { nameof(SentEssMail), "sentEssMail" }
    };
}
