// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class YearStatus_payroll
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(LastPeriodNumberWithApprovedPayrollRun), "lastPeriodNumberWithApprovedPayrollRun" }
    };
}
