// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class YearEndStatementsReport
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Employer), "employer" },
        { nameof(NumberOfActiveEmployments), "numberOfActiveEmployments" },
        { nameof(NumberOfDismissalCompensationYearEndStatements), "numberOfDismissalCompensationYearEndStatements" },
        { nameof(NumberOfYearEndStatements), "numberOfYearEndStatements" },
        { nameof(PayrollAdministration), "payrollAdministration" },
        { nameof(PayrollYear), "payrollYear" }
    };
}
