// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class YearStatus_year
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(PossibleActions), "possibleActions" },
        { nameof(Status), "status" },
        { nameof(UserRights), "userRights" },
        { nameof(YearId), "yearId" }
    };
}
