// <auto-generated/>
namespace Loket.Api.Client.Models;

public partial class YourcampusObject
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Url), "url" },
        { nameof(ValidUntilDate), "validUntilDate" }
    };
}
