<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>Loket Authentication using Refresh Token to create Access Token</Description>
    <TargetFrameworks>netstandard2.1;net8.0</TargetFrameworks>
    <PackageTags>Loket;Loket;C#;APIs;Client;Authentication;Tokens;RefreshToken;AccessToken</PackageTags>
  </PropertyGroup>

</Project>