<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>Loket Authentication Token Storage using Azure Blobs</Description>
    <TargetFrameworks>netstandard2.1;net8.0</TargetFrameworks>
    <PackageTags>Loket;Loket;C#;APIs;Client;Authentication;Tokens;RefreshToken;Storage;Azure;Blobs</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Storage.Blobs" Version="12.25.0" />
    <PackageReference Include="Microsoft.Bcl.TimeProvider" Version="8.0.1" />
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="8.0.1" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="8.0.2" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.3" />
    <PackageReference Include="Microsoft.Extensions.Options.DataAnnotations" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Loket.Api.Client.Authentication.Abstractions\Loket.Api.Client.Authentication.Abstractions.csproj" />
  </ItemGroup>

</Project>