name: Build and Test

on: 
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - 'main'

jobs:
  build-and-test:
    name: Build and Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2022]

    steps:
    - uses: actions/checkout@v4

    - name: 'Build'
      run: dotnet build ./Loket.sln -c Release

    # - name: 'Test'
    #   run: dotnet test ./test/Loket.Api.Client.Tests/Loket.Api.Client.Tests.csproj --no-build -c Release